apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: hydroqc
  namespace: hydroqc
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.4.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    image:
      repository: registry.gitlab.com/hydroqc/hydroqc2mqtt
      pullPolicy: IfNotPresent
      tag: latest
    service:
      main:
        enabled: false
        ports:
          main:
            enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                MQTT_HOST: mosquitto.mosquitto.svc.cluster.local
                MQTT_PORT: '1883'
                HQ2M_SYNC_FREQUENCY: '60'
                HQ2M_CONTRACTS_0_NAME: "maison"
                HQ2M_CONTRACTS_0_USERNAME: "${HYDRO_USERNAME}"
                HQ2M_CONTRACTS_0_PASSWORD: "${HYDRO_PASSWORD}"
                HQ2M_CONTRACTS_0_CUSTOMER: '0106492629'
                HQ2M_CONTRACTS_0_ACCOUNT: "${HYDRO_ACCOUNT_ID}"
                HQ2M_CONTRACTS_0_CONTRACT: '0311910204'
                HQ2M_CONTRACTS_0_RATE: 'DPC'
                HQ2M_CONTRACTS_0_RATE_OPTION: 'NONE'
                HQ2M_CONTRACTS_0_PREHEAT_DURATION_MINUTES: '60'
                HQ2M_CONTRACTS_0_SYNC_HOURLY_CONSUMPTION_ENABLED: "true"
                HQ2M_CONTRACTS_0_HOME_ASSISTANT_WEBSOCKET_URL: http://hass-home-assistant.hass.svc.cluster.local:8123/api/websocket
                HQ2M_CONTRACTS_0_HOME_ASSISTANT_TOKEN: ${HASS_HYDROQC_TOKEN}
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
