apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ngircd/ks.yaml
  - static-web-server/ks.yaml
  - mosquitto/ks.yaml
  - hydroqc/ks.yaml
  - veplan/ks.yaml
  - tileserver-gl/ks.yaml
