apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: tileserver-gl
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/server/tileserver-gl/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

