apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: volsync
generatorOptions:
  annotations:
    kustomize.toolkit.fluxcd.io/substitute: disabled
configMapGenerator:
  - name: volsync-queue-script
    files:
      - volsync-queue.sh
resources:
  - cronjob.yaml
  - rbac.yaml
