apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kat-irc
resources:
  - namespace.yaml
  - helm-release.yaml
  - secret.yaml
configMapGenerator:
  - name: kat-irc-config
    files:
      - config.json
configurations:
  - name-reference.yaml
