apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:WVd/Ym0+1v0k3TJ/o8mHMVlh7NbFq3MQgF5nJMnlDEDc232POfTaGFtsqQI=,iv:KUbgmpMQEHfLxmmjn7zJcEoKnPOPMIlQnGxfcypknlw=,tag:LhzgQRgOpcDnIeWl0MZLHg==,type:comment]
    VIP: ENC[AES256_GCM,data:KXo7MveWyFFoctdL,iv:9sxuWG5uZA2OFhPpjEOy2dptPKvINJRMhPhLWjW/5to=,tag:CnaurI7rLnNRmt1l8AMvsg==,type:str]
    #ENC[AES256_GCM,data:wcCIkZpGoXXRIX3G2xa0i2SH0o2AYdFpQEM=,iv:y8CiY+UM+pTOlG7kILjfcYPnHDIR0NlR5pRzX3FCenM=,tag:nZARfF0SMU1K8B47rFNr9w==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:UTAlTesiJR/WLN3u,iv:J7d95QoKlPxqk9DvJVvEuOf6zpGV0oG95u5po3wpu5g=,tag:YetYXySetmLgZ8HsHTpCJQ==,type:str]
    #ENC[AES256_GCM,data:p7Hn5duCdfGtUWGtqo9Z37Lt8NwtVHwGk5e8CFhrIoe7Ew==,iv:2E2YbROrzIf82t0T13xJfWJ0diU7QP5liJP4xfTvzIw=,tag:GjqX5xSAQlKSeazGrPwQnw==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:NAvGv93QOCthYm8=,iv:k/Z06D8EKuK4PHfRxsbk6q8oHQsn7gvWNV37EwBLskg=,tag:gFfXfvK/6ssx6L8YXkUxgQ==,type:str]
    #ENC[AES256_GCM,data:UxKQWRhBQ6IFwzGtaZ45NVXGA0axWRwUmAgvGQxIBG8eRmxrFDssG9D40uXBqzk=,iv:xHSLIr2dEOzxhyYe5Je/amLndc4lhTswfm8XMcuz4mQ=,tag:BDaaG9LwAaw3iVvaF6Ae5w==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:xfpL8IHwMBa/aNRHoh7QmpzTMPnA7cDTkwvr,iv:GcIR5WwUYnDQg/asDG3o3Ucbf2IRmAi6xM/rsHQUL58=,tag:SGfI3ULPPSlPEUKeTrUojQ==,type:str]
    #ENC[AES256_GCM,data:TNnWHpGoQUhHevPzrGZ5/Nr4nXrgRQuPCC1iT/RNiIiRS3Nf8fs/6CG1T/hmbhat66X7S91HJe3WmPllEqrFTmy0clrYJ8s1I2Ht4eiINRE=,iv:NpuLK8KCW8vv1seKxVd5KVtMbGoMu9P2yo99L5Aknnk=,tag:Pyqcx8oycypcvU8fPyZ/gw==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:XxMZ/e9OCyLYP+BGxw==,iv://Fo84xJ/RYyl0lozVx8UFX3pQq0/7Wb+KsR932zIRE=,tag:zBCmAzhpmy/xf5OjfCj+LQ==,type:str]
    #ENC[AES256_GCM,data:PQ+8ADyufq/l8bJE6TMXaHumtrEEil2ZkCm7rGjt3WAM+DcrrCD5Ay7RN4hZ0gxP9/Avv9UVeZQ=,iv:bqsAuzynt+FfbHUf1fsfQcozi/+C9FaATI5kxFeLxrc=,tag:NOgM/hZk2aTjA1U3Tz/r3Q==,type:comment]
    #ENC[AES256_GCM,data:SRx9b0Cu51GSGXxlrZsESVlmusEPAopHuA==,iv:rdnr4oxD+nbDZQwTccCgeG1piIaUcx8NFKyDBtOjVE4=,tag:7kD5ixBlxeO7G5Bc6D6qwA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:zTrpbid5ypY7BCsdkheORXazYZWmy4L58NPx0fV+bCVlHLKFQ2wR1VQ98g==,iv:80TNy3L3EqHM96hijfQ9dcIkPTYHl/vM4ptKghpRmds=,tag:Nv5t/uq0wL1+fVM/+JuH8w==,type:str]
    #ENC[AES256_GCM,data:MprEVGg6qpNgxsdL9lmJQbXHNi18WgzuEWoCwPs=,iv:RxfwSRlNRQ/LgyuPaUy6QA6Ap0EYd90QNjqFZMs/6fg=,tag:aAfDBq/eqYfexpLyrUUrqg==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:JgAl6J5C,iv:dOAQWj8AtkXzSZd08hmYB7fH0vpx1HHsEN4F0x1dBkI=,tag:KRoqLyky8WIlX9CisH+Cdg==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:3C+SB8Cr0IqXr2+C4LU=,iv:SyI6aRsEnlrzngfViWtyR0NN2POoclPya8ngMK03g7E=,tag:i+/CoLX6sIht8kzubRZ32w==,type:str]
    #ENC[AES256_GCM,data:IM7VXBXBkV/E10kGgg==,iv:1XE466akhjzJ7sRuNGcC2mrM91o/7hxBPNG7eddKt54=,tag:CU4TceUu63OlPZSFsuQqFw==,type:comment]
    PODNET: ENC[AES256_GCM,data:W/hbNcBRNTMOE+e20A==,iv:qU6R47L4PlId6fLo6N5BhMMR5Xhf7EAFxxL+PdjvNmE=,tag:JVXYKBkEa/QdRoJ8gQzkTg==,type:str]
    SVCNET: ENC[AES256_GCM,data:5juBVe0jLoDSCahSJQ==,iv:nz0guX3k2qcwRHsYsxOIbNJRUyIQwmbrD2xQRfyaIy4=,tag:3GGG6D8OKqb/iu8Wx7KTOA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:DRokVw==,iv:w1YHYCuxkTWDxoyxgBLmWfmim9ZQG1dYTWOBy8AZgu0=,tag:nve0iO6MK2TlAF3CYpfbVg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t6vcg85l9rfrhfh3se8qum05tc33pu0ma24vqfz4usz8yvaquqdqfpg3xt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBjQWF5dDhsL200NTJlVndv
            WXQyYkgxZmtpQnVoUzZqNGVnNXd0UmJYbXkwCmppb0pvNUZqU1hqdDVYS2FDbENZ
            TjYrRXFxbVBVUzIzNVJXRS9KZVRPbWcKLS0tIGxoUXlaRGxPbEQ3SjFLS3lKd3Vm
            cWhQWGZkWHdrdk5KdjJUT0FCZWlVdUEKUWh9uqqWpii6WM1+99Q8RTug8kkIKgYV
            DqD0wm6nxw6lHkwyHISICa6gmyx511ySAEWYheWhluPDFLktkqp8dw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-31T02:49:02Z"
    mac: ENC[AES256_GCM,data:DbuLv+sPVL3+NVDY65s2F9+wP6GP0Ow5xJYhdWiQhg60Vf8hFGLilj+2cWgs3MBF27Iy/aSAAO3ofy9wkua0Kc1M/MzIIGkmzHEpCTLLEFlbDKOwgiAEH2vf2iDiUdBedgn3FbzQZAEyKPvSmjFCckitFdsBUcXMrVGtiZSfWeg=,iv:KzfZenY4LJwbGxc/YkdM/FIWgZ4/hzi06OYO68kPIqg=,tag:yGZEbS7U37Rj1kz2jb6fDQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
