apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:ne3dTsQc3QrtdLEjK3TNaJ4Z5VwCYF8SChZotvXJp8icsCR8ZbYZggOd0Nc=,iv:Mv4z0WlI3pl+8qFT9oa4FGzhfgU2K8OENNlBPqiCGdI=,tag:ftd8hoH2W7KC2Xnri7MDQw==,type:comment]
    VIP: ENC[AES256_GCM,data:yN1MB51M0tBG5mH4,iv:chsvXCugQN/uG5X0VrS1IQF0eiqlDxTdsKVGqsfUdqI=,tag:uot0ze1gEIHtUWN6lyB8vQ==,type:str]
    #ENC[AES256_GCM,data:Vj2YuoT/diZKsI1aGDW07AIBCGI3j4zRoE8=,iv:RCDSC2g9GWiXo1MLd/dBXV6Etmf15kYtLi8dROIThG4=,tag:16kYOsqoGQ0eyWwTtZnLxA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:fkYBrl3TPQIKtuJu,iv:0n6UgNbAgQlcg4LrjYcTQFI4SEIpuVPd67/8VqMm0ts=,tag:lm0deguafeuK339AlB1dIw==,type:str]
    #ENC[AES256_GCM,data:KYL9ZmWhck4j6dZm7aQJwAzK2uPRcsCUqprgDzar5Gcxkg==,iv:ZxIS0AGiXGzWNf9YSFCXz6L63IumG8gnI6GiUuz4Ro0=,tag:YqZaFC2pFl5rtC3fhIoHfg==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:JLDywwZ17tiee90=,iv:zmmdRIq0M+VoKeE3tdMatiRzONQ0gVRjBEfKXo1dfXw=,tag:8B11xn3cob+oqCCJGuDR6A==,type:str]
    #ENC[AES256_GCM,data:f7tigVKlpsOYbiezxRbVNoc4GSONR5stTOjWkTcdnHPqwlWDAdt2KhvYWj7Ql/E=,iv:sjntOIodfQ0+rUQ23A03WXt35JW29NaMJg30P0ujfGc=,tag:2JJmrbpBk4lYSSxSNQqKZA==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:DOiu7enSZ8yvt/pWQAhuldoJIEcIMRcGfc2y,iv:PsaDz92RbSltoswdlN5a6OD03nsLPVTgGM5A4w3Jbvk=,tag:C4xpWI/5ZZ5MU4zpq82NGA==,type:str]
    #ENC[AES256_GCM,data:EYpIEEZ6gGR4V91MU4eczSAgCwSRtF4wMjX2+N4VBgRnf8qIlmYyTBQyp4UVy8B0tlsxoEt1I6aNatTrhYXcVdA48QXR1rqvOw+/T0zdvQo=,iv:kriiuDkIqSrOEb+d3jDJClO1xCdn/TWCcb/iD7cpg1g=,tag:fVyrYxwbsivwX+smh1IXCA==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:EOAKe1Vpo5LNL4yRfg==,iv:8GPWaG2qnsEUdv3A1MLpeHkquY4wwzJsmCflyFItxGw=,tag:BK9J2N1Pej325DXSt7i84Q==,type:str]
    #ENC[AES256_GCM,data:/Q14SYfwMC5LJTYApmbogAtMH/GG+DspHWkF3mmOVz2C/dBNfejprJ/q+jxFX5o7HT1mCQsi4d4=,iv:HZhD4YaCaBvkau0ALUin/Cc+PEwIDlmOD5Eu9Ywrez4=,tag:6oN88ulcGX59dWvgnSq/9w==,type:comment]
    #ENC[AES256_GCM,data:jAoXFU5ezKj7aXf7ViooN4Y27HtSJ2UXHw==,iv:CCLtZLH8e/R/a+aDwia0E/HE4Lyl2iHrE+s18dzQLrw=,tag:ZmMjVX0cZ3f2WQp6fDGYRQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:+EtP1P7wAHpk6VQk2uIKWrAHclI7Mej3SNT3EgvNpXUfJwSnEfEz7e0SOg==,iv:0a/zTREeXc2NUrbtICkCqSziZSO/q4PXeiax2u4MF1g=,tag:8+SItkD/JkLX0uTHtHMAnw==,type:str]
    #ENC[AES256_GCM,data:8MBueNWB3Q7Rc2VUK3PBvkkTlgl9ZKTOx65EU/E=,iv:Oepbp2217M3J/jg3Vn9XqkG7bTCcdLX93DDfviwdzPA=,tag:5MLxZTK3CCxOIHIVcSKyHw==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:dLQU8ON9,iv:BCUR1z+SAFE76+meb0xhfVDEacrQ9Iolggjwu6AjsA8=,tag:PAumAgHB1UIEOJbCD6YQwA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:Ww3DfUU3nMalnFLcXJI=,iv:KwgVHz4KXZTNobp14RNrRbBBCvniJ8uavnmXwKZr3yE=,tag:ya23jKiZRrLgfcUgUtRjEA==,type:str]
    #ENC[AES256_GCM,data:BAqgUlcM7SH2Nji6Ng==,iv:c1qDK+I3jPjFoxhPhZeBNvKuWzxKLhx/DZLqqu0/usM=,tag:FL9dzec81n9kyTylgxj/Fg==,type:comment]
    PODNET: ENC[AES256_GCM,data:VkIwI7dhCMr58kIsYg==,iv:tlT60p0e5QckfRi216yq5MNGTSadVWu7RT9GBEBLaWU=,tag:vNjnE+ObpL/8SoIRCyL52w==,type:str]
    SVCNET: ENC[AES256_GCM,data:j+DYKQNtkTgSEjF2yg==,iv:2dCXSW77W1OkVYkzbx/GzkYMW13w8prLSrinuBTYjfo=,tag:+UiV/h0yc+7kHgRmz2FPnQ==,type:str]
    BASE_DOMAIN: ENC[AES256_GCM,data:TDFqfHbL8ONgVxmKSAU=,iv:KkJmxqcb0lr21cuIeW/wZHY8G3Y4pf4r3vsc9CggN6w=,tag:0+BCQF7H+dlBTUO4IDmdpw==,type:str]
    EMAIL_HOTMAIL: ENC[AES256_GCM,data:WoPSXxRQy1z4pn/WC0ojJjQhr9AgXqw=,iv:bqanIksgmOaFPj/fuNt9xloGjuh9dIyZakCt14g5Aeo=,tag:ZNeFrJUilbSMfT3xtsrY4Q==,type:str]
    EMAIL_GMAIL: ENC[AES256_GCM,data:ZvwWZTKln/8KKt0rumOx3A==,iv:JuWIn6I3hoUZZVxMco4ztNdd+k5n65QN4DlMpOGVrZ8=,tag:/ekAqD7qj1emxlG/gdpW+A==,type:str]
    EMAIL_GMAIL_PASSWD: ENC[AES256_GCM,data:Carrxjo4ZsxY+w/V/QUtmQ==,iv:qNJKyI1kfrqiSLGB1HN8H+NVxrPOTKR/dcnXbFZseNE=,tag:3n/ZUfzjZEeQ0hNLGCvQFw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:+jx9qGI7mTGLsOGUaOm0mWddpPOS9Cmt9IirVe768F1+1EgrU+jlkw==,iv:baKYx9bfjnrBwGRCtq0oBz3VTIRSqd0vfZyA9B8U2Gg=,tag:ZQBAYhGtf8zNVV4lCSK1HA==,type:str]
    LDAP_BASE_DN: ENC[AES256_GCM,data:bQs6ALU7fyBSh/nXQ1pDQJ0V0PH5zx1zBvXWMQ==,iv:vLSlFRr/09kdEhuyVUmV+yOj1dpX3YskBmtGq9ipZqI=,tag:M17rv54AamIFqXOYNow6wA==,type:str]
    LDAP_ADMIN_PASSWD: ENC[AES256_GCM,data:zlsNuDzf5UlBtF6OvKjhzuk=,iv:IsG2ALdb7FgVq6zUvuaNVeE4CYtLKqA5vfqqde3qPxk=,tag:2KL0AtfnHQS+LuX8RHCe9Q==,type:str]
    CNPG_PASSWD: ENC[AES256_GCM,data:5w1gMeACysukHBdewMMMOPZPIw==,iv:Pv9i5L4glkHxzUJf0S4t4pLsERbyjXwJkZAKrQYSt+g=,tag:y26v4f+fE0AjaytyJl6avA==,type:str]
    BACKBLAZE_URL: ENC[AES256_GCM,data:zl+a2tEFR3Ld/xV381CMGJej1ysqo3mlV7KyorKNvyI4mukUI8o=,iv:0ra4DMsunSCn+AmuUAAgp94Ur+22VdWvRcCbKPlPxXA=,tag:JeHLvlRfl3J5aKxFVnjxUw==,type:str]
    BACKBLAZE_BUCKET: ENC[AES256_GCM,data:IduYv1jgpPJQoUv5,iv:EHTcU9d2g1tOE4Y9lmF3vMMnvKGH96oew1ORKPKpmrQ=,tag:6Gle6NPyfzvkxxPm9+MoCQ==,type:str]
    BACKBLAZE_ID: ENC[AES256_GCM,data:oPlSH+N5GxlH2VotzBztiNXj8UZ1QVMcZA==,iv:A3SpkLS9CNi+MDue8IDTMv6KoYqeETE+qll6mFCeNOo=,tag:oCgebXojX0kkSZBwdwhXWg==,type:str]
    BACKBLAZE_KEY: ENC[AES256_GCM,data:HWqARPhG4n5HOPnhbP+FY7Xfy58KRFQfbrc4ZVhTDg==,iv:K5QvRX6XnXlE7A2u187IgSneOcCXCMVWq5ROeiPKZtQ=,tag:7jTzdE3icas7egqhY5Q6Vw==,type:str]
    BACKBLAZE_ENCR_KEY: ENC[AES256_GCM,data:zrPc8TDs1xvZ6vRAZbBFVsE=,iv:+NieT31cQDjycHGtTz7AhDap/HfAmKRR7tIgPCgjdoc=,tag:h5rVRKIK4xI2sNxgvXlhDQ==,type:str]
    DUO_HOSTNAME: ENC[AES256_GCM,data:HtK7bo+V/B5IeJPrVzOfDvUVuM2xi9sKVJysyQ==,iv:xNKawVL4B8RP8YoK34duSAkWMiRsrk8iW9OszAiJIPg=,tag:hpeey7RaPFLyYJ6dyE98lA==,type:str]
    DUO_INTEG_KEY: ENC[AES256_GCM,data:ta6R8XHvL3gfKit7ztbXz+XgXzg=,iv:tTAq3Bp0bEmJtqZypNdRCod2iLkYdlYgyBQ2GswPHHc=,tag:2May277qp6g6+J2LXUVE7A==,type:str]
    DUO_API_KEY: ENC[AES256_GCM,data:t5uDhdk6BgVHWSOIyps1nVIbQlGUj+JGR8lsLXo9xquVNgXrNuz5VQ==,iv:ZFaHxVcp2NtE9JVEymeBTlM3k+D3ZwXy54KT1LGEYzo=,tag:OTdtKSgLCsRMxrQMMBlpyw==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:BaVp/A==,iv:6CpnbeCnupfw52bsGmuishMP+O/d8vRsbBrAuEpz+RA=,tag:xG7waZI+ucqKZZ9mjFvQhQ==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1t6vcg85l9rfrhfh3se8qum05tc33pu0ma24vqfz4usz8yvaquqdqfpg3xt
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSByZ2Zoc0hlMGNJdlNoRlFn
            RWNMK1M4dS9RaDRqU2M0YUFXSTRoOXlidUNRCjJ1bStnQVhBQ2VMT0d2cjZkOFRD
            ZE4yYVFBdXdjZUkwOWNOQzdyTU9uS00KLS0tIE5BQ3JXNlY4V1FMUjJGOWRhVU5Q
            RHhKVVZaSFIzdGVyWm9NblJ5My9pU28Kd2SQRueLKZIQK8ZHLA2gbgTndjeGlLgw
            4hDJh6RxZhV36fyYHNG0Nw6VvXOf5BBtf4HWUZ/tJRUXWzXEj2jRrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-01T17:50:15Z"
    mac: ENC[AES256_GCM,data:tcQughOQqk9Fv4BbaVj7A3NQ/OOvdARz3vRpy1iWodpY6hLqltWSOJogYMOYHDUHQz/OgnEcAKCn0XMiR4LwDQpyfq5Ua4pGCGruXX7w2JPUG3t4DroPXM17eQlrvmG2hioGVfOcVzqfdz7uV6UbWnFYPiAdPThy9tLpz4Qd8Ws=,iv:iob+yaj+fryLT0uWYsq2z3lNVVDfKI1fhL9KdgR0RUc=,tag:HaM6YBPc2iVpkVFnT5LFrQ==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
