apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Npc6UVhMfqgwjMljeJnTCqdgs/znris=,iv:F5Q1hPW4CVRW05UmnMTdAP134a6VCcurqdsu40QZkDw=,tag:JhsbIK7yEfEEPmpLzEaVzw==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:8SxolRwTwmqpEAPIll7PR60ZC4LJsQLTFvBC/JjsqeOdlepN8DOUCOt2xw==,iv:BR7bsiRnt1oWEwYGMinuJokZYSyVROwWyJEi5sb+xEw=,tag:ckaRuLURRM/Fat4Ao0HVrA==,type:str]
    GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:Bnhewl376r4fE7C8ENcT0ZZUkD4UvFGgKvILnBqA5KVGs6+xUYOvIg==,iv:nN/uGmoAhCS9YTRqNKFcK7Fw1nFsqmpx5n7KOKdCcw0=,tag:LRncmvCucN2iewxqKHo4Sw==,type:str]
    #ENC[AES256_GCM,data:+V34+NVdt5pDr++r,iv:x9SVoGWEImRQjPNGNk/32UZuWeTkKP8sGOA0xcLkdOM=,tag:EOvj5HCEMfKwpCL5b+WKyQ==,type:comment]
    VIP: ENC[AES256_GCM,data:NetSh65dvqmjuuK3,iv:v7WjM7YXQdWPxgsjomeUR0RznONIbldNi2ePQdQELmY=,tag:VhhDbMPdWFXFeL7DQD+45Q==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:/bb/W+a4CTnZVloa,iv:CPIRtiVd2DWr2xBKB2hG/QVzpWCRKFReM4k0DmewodQ=,tag:rXTtq2V8di32d1Leog/7Ow==,type:str]
    GATEWAY: ENC[AES256_GCM,data:Ci/GKmrmKby8GaM=,iv:ieLiZLVZcvfgCNv0iwlpCjLNHP8xy0T81EfdLLrjbak=,tag:C1GBpG5LUOGIxkiXZG6cOQ==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:JHaVekmYJgysmCku,iv:KTFeZqWnsmXEV7Q7i3iKcA81KPrJzSjys+kdYaP9Hdk=,tag:oSAE9TtjBkHGl0ieXcFONA==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:32p2G7M7ZoN/uV6L,iv:6WpgkcJAcQ++X3Fvf2YnGN+ilnVmpmide5KKdSZL+1U=,tag:jjI0gW0sN/mh7hJTyLsLiQ==,type:str]
    METALLB_RANGE: ENC[AES256_GCM,data:usmih3jYiWy7H5lMJw2+5BVcPRdg3wb4OKif,iv:5mmGXBBUuZv684CkcaCHj89Xv5+nJkUP2U5ua12XUcs=,tag:ppTgvBsAEjTPjLybfZJQnA==,type:str]
    DASHBOARD_IP: ENC[AES256_GCM,data:dN+8k2hq6T5vSuBOSQ==,iv:lT+4kXrho/tHd26eGY62WM/AihVIT1zoY+YcAqFqAQA=,tag:G8u1iKyNY75JQa2Xu302gA==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:IHrq1aJdwEo0+/vSNw==,iv:Jg3FuJJn7aJkl5NeqFCR/cJv+NFAzfn4PJuop5PHc+g=,tag:Z6ELMRPXKVGuuBXjzv1ODw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:M4Yw2+VaiJMq9HSMxA==,iv:bilWShvmdMTUcszjIrL6IHPbev5bHO0Xe5wreJJsYN4=,tag:tOBjflIKv1v/60gI8BN2bA==,type:str]
    #ENC[AES256_GCM,data:dCzkGNpeouQDoQ==,iv:M3oWwf2Dij1B0Ke0+D+bEd5Uebz9csjv7znDy2z9Cbk=,tag:ERRHfAtwwHeqwaYMl17C9A==,type:comment]
    NFS_MEDIAS_PATH: ENC[AES256_GCM,data:grw8fUsKyO7LiavhdX4m3+lbTloltK0=,iv:Jd2xzfkcX61kQEmn7Y0BPuzguUEV92qYJ7vi6k5dzLI=,tag:hvzphRVXh55CWNX5kd8RIg==,type:str]
    NFS_WEBSITE_PATH: ENC[AES256_GCM,data:H8sghFUClQe0L4J0OUUaSuQT8mdNLsjGayjbPsM=,iv:c7/IS++GoCdvnqMIhpvdNn+2GC8XpRmig4bemkL6rNM=,tag:EypqgMoWh2OPX+1MZ7TQsQ==,type:str]
    #ENC[AES256_GCM,data:D7sPjtYmB8GZ,iv:a4AIE/P1Cs4qcfUMeG8u9/OkUz33+WxZTJTwM9VT2GM=,tag:xeHXjqFIv12wb1CXd/gVhg==,type:comment]
    NUMBER_OF_NODES: ENC[AES256_GCM,data:Jw==,iv:yLIy8H3OH3oDyP4/sELYG+8kDlL1nOoxDYKiMhbmtCw=,tag:q796zTjLixjPUXa1Pwp4og==,type:str]
    #ENC[AES256_GCM,data:yAq+beowaA==,iv:NISki/mvOVse/Lf891nHCfIq8Sv8WiSkRrKzXsLQeZU=,tag:UMPGSwQS76d/iL5wu5TZBA==,type:comment]
    DOMAIN_0: ENC[AES256_GCM,data:0GNrbbEydevh61uL/Fs=,iv:jYk4fMIuE2ZMlVnwDA8ELP9FC69SgQJBZd2h6/y745Y=,tag:ia9lLmOeEmj2qaSTMMmA1g==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:o9Y5Or7EQc6noY+l8sSekFQ4EHzBmCg=,iv:D4RwDeL256CtrYuxjbl7WAWriZ2VFY4UuD0JSEjUGZg=,tag:j6Q/cRV+PJyv+7UkaVYaKQ==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:gv93wu983GNXSmjH0nWCVaqpbXvzlyc72u76pdn/cwG8oQV/gmH/WQ==,iv:aTlFWbvZzupf/QNY06yrSG4lnUdkmabbOvEDyt/qHsI=,tag:vOLKpbLzseFduCJRJT9PKw==,type:str]
    #ENC[AES256_GCM,data:TASRRCDARQ+fbHGfNRu59dzD46BgaoMj,iv:8xoGFdPD1dW1Nk5kJvopQzfxi8HTAZ2zH1EJF8+d49E=,tag:6MjlgTANRnHpLvjluFp4gw==,type:comment]
    WG_ENDPOINT_PORT: ENC[AES256_GCM,data:lzJA+Q==,iv:xj9w5n7sBtei/HH4RsmXuaaFnGjhCnB9WqddPYSVG3o=,tag:sM2OVT1BCNr4ziOCtN9sgA==,type:str]
    WG_SABNZBD_ENDPOINT_IP: ENC[AES256_GCM,data:uNsNKRsyIUxUsJoyUQNB,iv:wIqV2VFUEwzNPhWhiePP149R2awxKOahFd/SnLKNiAA=,tag:821cFG1f3fqIRpzJO+XFQQ==,type:str]
    WG_SABNZBD_ADDRESSES: ENC[AES256_GCM,data:42TtZPLHKYEs2qoVqezW,iv:aogshD7u34BxT3bM2Pi/VUG2OU19oB1aQckq9QXmjlA=,tag:vz2y13uW5XZ2Dezdji9kfA==,type:str]
    WG_SABNZBD_PUBLIC_KEY: ENC[AES256_GCM,data:Hg351JFp21EtNXmixk/8EIYpk2Zd93HFkI7Ijzu9ape3dxJqjk5sRIrqEO0=,iv:h5wgSJvbksZTjxPKTn5n6y9/ScClt6fbkx1Sye0i/w0=,tag:UIb2sC3wirJBnYbYBiWEzQ==,type:str]
    WG_SABNZBD_PRIVATE_KEY: ENC[AES256_GCM,data:ln5p9fsmD18lR2i/+GTaVfeluqom/T/cXUG/U++NXVk4hULYGyIhLEh/Suc=,iv:VFQnLW7OhUZ5X/R5RpYx1HXJc2qmNLPCVO03hbJgsDM=,tag:oeL01VuMbF8ydYfAwcMoGQ==,type:str]
    #ENC[AES256_GCM,data:SVuLt0ybGQji,iv:QFwaxIZA0tyx9SR/jXHGrWvkQTWlxl++pNsz7C8NWvs=,tag:E7VStbTM0kbW9HzgBUtYBg==,type:comment]
    SABNZBD_APIKEY: ENC[AES256_GCM,data:6H5FSI7WXzuE/ZffGqe3ucIeq0plKyNSBlI7FALP2pU=,iv:xqQyd3/X4Ol+Q4eBt1ekQu+bCNb9qwdXThVx/K+Nffw=,tag:eApGmANiLW4Sq1odQjvCjw==,type:str]
    #ENC[AES256_GCM,data:jh5MxaI=,iv:VMb5pLQ4gJkCBzY4gAo1eYkjWekyaK+EZCeFehtLJUY=,tag:Bc8jUAjFeNJz9jig8uP58g==,type:comment]
    LDAP_BASE_DN: ENC[AES256_GCM,data:8bILZkcI6Tc3gkmQRiqXOx4Lmv+6xOHbAL/nIw==,iv:YHq5klvEt1sZTqPSufO9AjeeWC6u8Z/p91VbJfokagA=,tag:ROx3EWNA7f2CuPrlNp4yiA==,type:str]
    LDAP_ADMIN_EMAIL: ENC[AES256_GCM,data:DnmvsdWeYMNVuf/DkKyBLl4=,iv:QcbnY5AHXXXtlzAqokxH0hF7rF+2obGXOO9Q+msR8dc=,tag:lc0Qf3ga/OP85ziJOQ9GMw==,type:str]
    LDAP_ADMIN_PASSWD: ENC[AES256_GCM,data:L1F/8kOAxFaPat7upPG4Gdg=,iv:Qgx/SqBV2Xx9H/C9O4H7jkE9zIz5E8uBchNjDj6/gnY=,tag:RbNjA06Yg4lfK7h0FecjJw==,type:str]
    #ENC[AES256_GCM,data:gxI9sLO4EJvh3QjCqPzbjfRsJek=,iv:40S8BWeoC7uHvwxS+OcyMLy0Rptr/l5iU/axnaI77hY=,tag:7Qk8gqUa1g0yXcdbEStQ/A==,type:comment]
    BACKBLAZE_URL: ENC[AES256_GCM,data:HME49kOPjTJqYshXGPwuelUh6klpM832dL0CkirnPVl58QkUCdE=,iv:Cm62i6kTQjKurI44iiPBCrLdDJyPO5/mQ8EUWEXxg74=,tag:jd4a+mkfqTeaFSxj46EDOg==,type:str]
    BACKBLAZE_BUCKET: ENC[AES256_GCM,data:u4XtcPQidRsYGny0,iv:WccdggBbM7vZCbLObPoBJpQXroNjVkbXWacbY/3JBrg=,tag:L4JGU/xFC1hBQrInsM/o4Q==,type:str]
    BACKBLAZE_ID: ENC[AES256_GCM,data:l7d8xFEQSVNKMRsnMzzA7HhSA7CXPz+g8w==,iv:NabWwK1fucR5jp7h5lpvUr79a7DIgrG3h3eMCIHFNQg=,tag:DmhcfljD1D3ZQvXQ7TcpIw==,type:str]
    BACKBLAZE_KEY: ENC[AES256_GCM,data:xO4hByyQqom94qKz/FQLCBcViQpPssxuP/EbPaTuXw==,iv:AfbijhZ7eR91SKCY/xnMu5OKxVXwN/c1mIuBVhmEM9U=,tag:ZLp2RITOPN0yCyQDOd+k4A==,type:str]
    BACKBLAZE_ENCR_KEY: ENC[AES256_GCM,data:fu4KxWYQaPFQuFJlPoDlsFY=,iv:nILy8RdxrtBPynmMWIaNF9XUuWwmIadCMWs96k4lHZw=,tag:U5tqKS5pp02dkKfP0K8BOw==,type:str]
    #ENC[AES256_GCM,data:YN/X0g==,iv:bIlltM4mQpjuXmMbL7Ks8IsdmJrYuZK5JYsDhEag/1o=,tag:5LQUL4Tsz9SmOiRkoWhV9A==,type:comment]
    DUO_HOSTNAME: ENC[AES256_GCM,data:9VdWL6+12NaqfeUKFF7FlQ7HdTAmlcOgtqxqcg==,iv:rUNlf/ZCC4eVINbhdUzJhGT5WzW10eB66t2IYf5Onfk=,tag:HxPA1flB11raJAf96VuQsg==,type:str]
    DUO_INTEG_KEY: ENC[AES256_GCM,data:Rd9kxg+QFI5yOtBWCZqEAqqOq4s=,iv:4k+koVafx7TmmXhbGHCLX85X+0ln3/DcdxXuxjCyB1k=,tag:0yrCbELefKLiOWnh+ad1dw==,type:str]
    DUO_API_KEY: ENC[AES256_GCM,data:jIgXOve1vq2DdX8T7V/Q0d3yBJN+Sk7iIV05nghk6gzDs9JSNowWYA==,iv:siXGm5td9ib/zdzuxyxsTWxxEk7OpckbZBt5uKYxn6M=,tag:UWQi/DI4SotXgqUmHE5ccQ==,type:str]
    #ENC[AES256_GCM,data:rgXIE7WGuWWfl+3y6nfYoLl6,iv:D8Hc62fIf/N+2yd2mSInnmYgkgu6rEfJCeToNcHuhNY=,tag:rUylrCrRphWkLwDNfg9jdQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:PvU396pu,iv:s/SRCmtl9zA98OTqHqEvlFqszoGzJpOfr99WEynKt4Y=,tag:Zc1IGLzDn7inFBDbdR55PA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:3WvxNt7SITEFBTiWyFw=,iv:4s+6o1DQCR5ZjQWPM5GwIRdhjDPpmJJIDzpzthgxkJY=,tag:z1H77xKk5mbfoSwokgPw7g==,type:str]
    EMAIL_GMAIL: ENC[AES256_GCM,data:F4NOafPvtsX7Ani0n1CI4A==,iv:vtdCU+XZgWVCoxTYjdUIGcNenkta/+QyTC/BPdoT2HU=,tag:UhJWDSQnEYQz54Ge+VUPrA==,type:str]
    EMAIL_GMAIL_PASSWD: ENC[AES256_GCM,data:Czx6MsYxfCmJ0vnWaFw8vQ==,iv:UKBVi2CiuMF9DFyFISiOn+jB7IuS7sYC+W5JLZ7arC0=,tag:VexayzvULI5S71h2R/cG6g==,type:str]
    CNPG_PASSWD: ENC[AES256_GCM,data:SqkG4zLxbS4MoBwIemYgGpF8BQ==,iv:KZsH4z2TufhYu8RHGHetjCKOXyK6Gv5c1WdI+1yuDhA=,tag:hWIXF936+Am8/csIJ5B61A==,type:str]
    OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:BE35HVZn4gtVXTU8B+xSXfMndR+03hCCLNzUSdgKx0g=,iv:t6dxS7D7DFRUhTUdEP78cxlqlb87bA1ywaHn9ke6PVE=,tag:Q1m1yBV7NIYZBd+duwtkAA==,type:str]
    #ENC[AES256_GCM,data:Hc3sDZRyQw6spBu7G2w=,iv:gew+zqu4CqI6iZw4cL+TIwrSh/B265QPcD4wfCbZJXo=,tag:43YqDea9376zZu3BC5WS9A==,type:comment]
    PODNET: ENC[AES256_GCM,data:08Bd1gfz2VO198h2TQ==,iv:T2sg+hchK5za54ha4g+y9AVUuOxHrLFkqb5NRAcbPxs=,tag:fo7boNPJgkphifZLnLjJ1g==,type:str]
    SVCNET: ENC[AES256_GCM,data:OVWNjSwf+DWusB4LzQ==,iv:fuQx5XDJxBvsZ6SOJgnwP+EVzf8tygGO2RPXqV1L9YU=,tag:U38Xt0ZKj3LyqZNsCyIU2w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:7X6Crw==,iv:Magwo0ASw1w9k24MGF6VgJrXc/wcperQ3zNe8VWmLcg=,tag:D82DGZjVX1KHQwkTh+qnpg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB0YURTTmpzdUJJOGowVWZy
            MmRUZnV6L1F2NGE5eGcxTFhqaXpGQ3UzQWwwCm9MRDlBRTlWV1FjOUthaitZUWFq
            aHJKa091dEg2MUdHeC9FQlg4Q284cVEKLS0tIERQblJSNnNaRW5vdzN0SDVYVlNa
            N2s0a2UrL1B5Y2t1Q0tpWUVmSzRUWEkKAvXatNO4iN3K+cbiwkRV1mhuKAAKnN20
            UwpfZICIURxiieHe7OuHwWl3Y6ReJkNIIckGNjtvUtTElIq3VC1VeA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T22:04:10Z"
    mac: ENC[AES256_GCM,data:nclc34NfxuchXODpb8V4bZmdEhkOP9E0C85CsyN1OCHn06sdDMwXHCVLev/ZxLnBz/ysp+tjV9bYFRcWaX9E8SofMg1Oe7GCHsfLFI9k/r0tPM0MN4DyMSDvWSLDEbTvb22u7hNkTvjnfl1pFia0idaSngO0tGCgpX0e7yzi4pg=,iv:pgg1TLO/4GtOKplJEvSNrrv32HDdP2IYjd8VfXHh8UE=,tag:l8cceCJXfrguOBEOJVc+fg==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
