apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:Z8+dsmVba7z9MC+kLzPFa99n3jMme2wKsHGhL10JqgdYbS7qI2UXlnmu7DTxk21H4QMHHM3RQIQ=,iv:GVBjgwKnWfHYTcA61wEMpe0MiHHFr+L7r86rbrsDzgg=,tag:oid8b577l/fcrUTBqtr68w==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:t7nipd/JsQaJLEZwe+7wRL0/St+2HJcthXShdSPwBtL4CAXsolPDcIOb/Q==,iv:Hcnz/y86Zq7wEpRrP6MeBdHxrePE2zpyaOlWNfnkAZg=,tag:4YZjgHJ8+ieWJ5dFjSaOqA==,type:str]
    GITHUB_WEBHOOK_TOKEN: ENC[AES256_GCM,data:MPwHj8NOYLQjTKpTSl5mKrGF/0/u2bUW10eQ3qnT+c/lV37nalnVHA==,iv:otgokoALfr4FgZcsU3Q2zh3gHYSmPJPwjuys2z4ChNQ=,tag:uYdntllGSoTytK7R3AZVRw==,type:str]
    VIP: ENC[AES256_GCM,data:hy2f0I7nM9BRaFiI,iv:/0X9PvNxETBHS3CAyZpzmCMRZSyxCeP71Ot8gX8N5Ws=,tag:NBJURf4Ko3/6XlHWaQhZrw==,type:str]
    NUMBER_OF_NODES: ENC[AES256_GCM,data:dw==,iv:OIKbubEtUPgztm6rpdVq+5pSYi7WIZpvdMA0Cgu7DNo=,tag:1u6aE4emvepLe5nYFQ7nzw==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:FSqToi5tF+WuVoBz,iv:pRNvN7I2SRiO1GJ8XAzSrgrmepdabj8EI4X9haCzgtI=,tag:y2VW66MJ2ObyXSgdufJszg==,type:str]
    GATEWAY: ENC[AES256_GCM,data:STYqIZARDi9pZsQ=,iv:a36Nui5SHzjZA2OILuwc6qI2avMGzTrqRRcdBjOf0sY=,tag:wYrwK7bPp2xHvDmqfowHZg==,type:str]
    NFS_SERVER: ENC[AES256_GCM,data:dsGzNVkmaXwlCmhA,iv:NwKxYbGOSGxG96bCPi99HCo8eUWEzIdaukWvVGmBBrU=,tag:+VG3GONNzp1oDQoMwXIrPA==,type:str]
    TRUENAS_IP: ENC[AES256_GCM,data:RwAZymmaPQOoanUR,iv:GSXklNcoFmQ79hwOdpiSDXoeTArHK6y3gsJo5ygVxMA=,tag:ypu76zc9FtdCPO5Zxja6oA==,type:str]
    #ENC[AES256_GCM,data:J1Jv8hMw78ftZhuTM0wKE4GP+lYtavjUF6wrQ7nd2FRqjbv+fron8zYrRPWaxuw=,iv:ZJkoMEuXersAxznxjcEqv1oB09Ll+EwJEFE0M9cT8+Q=,tag:NdVPhDN7+1hjqcNe2ctmyQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:CXYDyZzpA21iwcTSlklwzLO5WX2HUbC2D2fu,iv:+BAXzk3n4XBZThGbgt6rAaUAMbGJYBzx5MFLAcJDsPU=,tag:HGgcZdggrStEShNN4kGRbg==,type:str]
    #ENC[AES256_GCM,data:sIXhnWz66zWl2jCE5wpQXHH37sujAV+EOYKIsf0tgC/5s8nFBEW8rBOH,iv:E99fan2nrWuBKJdb8HbQnUq0SvDHFwNffAGsUPQiNuM=,tag:uLANeZpl2ZxhMYs2azVk2w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:VvKc2G4titubwv9i4w==,iv:nfpnGTnW1Egt26AqtFW9SRFbCifZZiyR5wWSIfhY29Q=,tag:ebvllxEjay5pIhuoPeVZSQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:PZE1nR5/jauBiIXcAg==,iv:tOMs9sepYef5N4feWzbdz5rU3+oDwKk6UwpvdczwfWM=,tag:axqCE34ZvND37k5rsnp2jw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:ew4hEwQGjGQ8MhKmZQ==,iv:+qNkrm7+VswN3nV86qXYKhxm1AB0SUcH3+I33aFOEBs=,tag:ghl8DVR9Aag9Ej/29Nbreg==,type:str]
    #ENC[AES256_GCM,data:gEmTcG+9/dvN+WmD,iv:ghaGl8RA11B/bS/S5JsEGWxGgAIsOEqGXS4sqfCHAbE=,tag:iIU2Y/KvraiUo5CnXrtv4g==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:QE6rYkpe,iv:3yfI0osASF3HgENyfGe6E+shiubRSjt8abHzEnhsg2Y=,tag:xiIQvWOWZ61UjKGXmK89yA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:LHIeXONOn3H1Fw1+NqQ=,iv:vwKEgqNqBDjaCeA3u1GIkusl09XSuNhFDM67jpBgZdM=,tag:KVOO7gCMxZp9BY3efJAG8Q==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:E1eiwotB6buswEfHIWQ=,iv:kH68ZNk37XX74RRQbqkl4x9u/FOzTTM2WtbDFe67CCQ=,tag:Yf8Ri0ZB6a2RipVspgvDzQ==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:0qIs02WtBZsTpBY+usSPIWcQsUFXHtc=,iv:sdWEjb1BnjVctQ2UFFClfoy+KAgnkYosxxg+7gRIh+w=,tag:ZqygTMNFuXppVIP17kyZSw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:R9ne6k1J1f5alZqOc+rVlUN9m5VDlz1JXAWY0I7/9js3/uL+9+nSeg==,iv:biwsQTrjYUXwp6kQa/cZ5wdteL8HfjTXA3CIMXxWuvY=,tag:36P6VvgW80B0VUhPODIWEg==,type:str]
    EMAIL_GMAIL: ENC[AES256_GCM,data:mVVu63R99PDDiPqjtrzi1A==,iv:SeHoDZFoXJMFw7F0wo1zPoQE0BWyJiGuxj/dHVJgJFQ=,tag:z/w8acBzFDI3evS0kBBIvg==,type:str]
    EMAIL_GMAIL_PASSWD: ENC[AES256_GCM,data:kkycv+BFPJzscswt/TIilw==,iv:pNPzHrjEa6i3a5geKctuM4Wl0B/37vOdgpxtjvLSSXY=,tag:eiF2gMmbKzSoRT28c3Z7LA==,type:str]
    LDAP_BASE_DN: ENC[AES256_GCM,data:pp/yV+5zk++jnST+rhT/V1HmggARI/NXTmGnqg==,iv:k2Xl1POFoyV0A2RnZ38PK+Q5/TPJ83MXpMPgaIeS83Y=,tag:PQ9Srw/NNk0RYq9U4oZyRQ==,type:str]
    LDAP_ADMIN_EMAIL: ENC[AES256_GCM,data:6QU5fYlj16mlBUyZMDYM7y8=,iv:adZd5IIvBDO6/u/I4OX30RV5Tu612bnSpBstXpKwf7g=,tag:Vl9kN/ebJK6uV+k3qVc6oQ==,type:str]
    LDAP_ADMIN_PASSWD: ENC[AES256_GCM,data:ZS0QnrwZLqxgAxeoRb6SPko=,iv:QbJLRouoyP6KzBSib3bDc7L8l+ug0frDelgKOXzW+6k=,tag:9vlca+hXp9JbK7vBXTCPtQ==,type:str]
    CNPG_PASSWD: ENC[AES256_GCM,data:0X53SHBc4ifBXvMDOkDASN14+g==,iv:zXHQsRz6xhXAt/BIfb6VEkStYaxGQGEXXrXI2QSN1/Y=,tag:P9MFJ5qpmEin6KfAsQmimA==,type:str]
    BACKBLAZE_URL: ENC[AES256_GCM,data:dujUJNoWt1u8kHNVUivOUqRwkn+7BJauXrgOAOzOSum2je/GC54=,iv:673TMxrO40rHr3ZU+FqOPkEQeNTx8XihJ8yzbzm7XQc=,tag:77SzHrwohsCIxluXTcnewA==,type:str]
    BACKBLAZE_BUCKET: ENC[AES256_GCM,data:RjyHEblZEy2QPNKj,iv:lVgWpSF2PmJJhi681qkO+Db7JtR69atLQnEZeF83HIQ=,tag:aGhy1FzjZJlWoB6Kgwyu7Q==,type:str]
    BACKBLAZE_ID: ENC[AES256_GCM,data:APPZ/zWeWlyOdhYRQR1wHiz7E2tyHWkP+g==,iv:KmCQ9phGJVsV7rurzCGsOnxeUXiphclQSbx7q7TzepI=,tag:eEtrYhqLuSmeEcZWw3g1Gg==,type:str]
    BACKBLAZE_KEY: ENC[AES256_GCM,data:qCyi7wPhTdDLfRZJhKB4048U6UAQLFAORsZ0LcdBCA==,iv:E/DFIINtxPF0zyrwLUxoOW8S5+akU8QTvM1OVz885ms=,tag:vPzD+Dt507KMiFANTRRK0w==,type:str]
    BACKBLAZE_ENCR_KEY: ENC[AES256_GCM,data:oO+MHju9DrxmRE85Lywm4Ic=,iv:jI57xGLAnIScsAAaBgkE4uSGhq46xUydvAWpfKdjfeo=,tag:/3L6PNsjG25dsrpk2idYhQ==,type:str]
    DUO_HOSTNAME: ENC[AES256_GCM,data:miXVIKXEGUCktmk+OOqr1rFS2GztLeGRiZHuNw==,iv:N01zQw8DJbrJ2UAX856rqhpE3UYogK/d5/wXEnbryHo=,tag:b19aR+Prf8VbpT6iZEq5hA==,type:str]
    DUO_INTEG_KEY: ENC[AES256_GCM,data:pZ5NN+glmexB+fOFCakxWUPamck=,iv:KTQIvO1bXqCGh9UgpFqF26qHB5kwrDdSzhWeyf40zmE=,tag:FFZELp0ukGtVjc+lIgkTPA==,type:str]
    DUO_API_KEY: ENC[AES256_GCM,data:dsS6g9qI6S5mMp1F+46vuUh0JdRId6dn+dR6oiosRcNs+N26cZDuOQ==,iv:RJBGGnw4OynBv32dTkinY+CfTCKbutMtRnW1pztH6CQ=,tag:TTbMzoLKIGjxWbMzVtva0g==,type:str]
    OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:DqmXHZy5WikRKZ9cxUdB/+UjMZaWQwMVNABp46mKExE=,iv:kq0iQaGsbI8cpFVOe8LfuStP41lTvTcamqJUK85y4JI=,tag:vFhuhZyTAb1mfC9r567fUQ==,type:str]
    #ENC[AES256_GCM,data:HEdnUxPZd69gsO2kYhs=,iv:TQahoNZhtJVGAbJqIi4JCno9VaHVBhVUip/UL3N8zV4=,tag:YxfN4W+YTqS3QKG9EMFKhg==,type:comment]
    PODNET: ENC[AES256_GCM,data:i4f4VNIP22W8KnJiEg==,iv:9VTjgLLZzs7pLeZlRW5g6dbn6WlFRL7AHCSteOsTofA=,tag:rXrF/FmtEPCEzmka3o9VQQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:3F4ydEZ8TptPq/QZog==,iv:XVMasaQDSgM9VFbYZZKLH5fwoLH+XFnTCUcyYFo29Bg=,tag:w2w7V9BToMRgHZ9uCuPYoA==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:mjHeRg==,iv:ui6qFUjBLTAfGdSaRkcWvFqFIevrQReIBeLBslQpsew=,tag:cImxNJqwHcEXuiDrXXjFLw==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuV0dJRy9wcExtOElkQ3BX
            bURzVU9XRmJXaklCOEtETFpVVko5RERWWmpNCkVHeWlLWGJUTkFNbkxjbG1STWpx
            UWx5a0wyNjFkV3pJcFhJTUJxZ2hQbjgKLS0tIGowVEc1SXh4U1h2MnZiVGh3akQz
            VmE1T1V4Qi9hUkpEdDBqODA0TXhhV2cK51cKMmyo655vRqXmE3bA7kS5u5dkYNdv
            PWPZqGNPc1yN1ffvK27NRLE+nZsabwExPkRDUN3HfzFRrv6qyEI1RA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-26T04:58:23Z"
    mac: ENC[AES256_GCM,data:cP4FClAqbsdjPJRd0HPyBv1SYPhq8xVSz9R7XYtJ+Okzp5w9rgqjn4xRFW9sVJxxy+/1ED30WZHC9mdGXGtv3MQo9TDJgWENKICaoTUOd/AnfufFQ7ft37WtIAMMVM0tcxb9GnCMdV6fq4SVMLFrC70pdMV9IcFIu7X0HmsjNdk=,iv:IjN5TxGI4q/H1SEZCO8pC8PGZx1C2B1mEmTBTFXoQec=,tag:l8GgYekEVjeICuHLttL74g==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
