apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:+jkCFaAxG/waUQDRDGqYjbRbJiF+oHM67DRnVmHtN+MZ3DkmrEoRmOhLX8Gez+z1fW3QKGYBbHQ=,iv:mDblMxfSWOOQwq4cjckTvYzGfr3u+mAiAkWDqTs9hHc=,tag:SsjDjN/8e24AJzBVULs+EQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:Vt2f/wreANuzHItCmzPPdKEG5z6bmuA7zOYm1AMZFqG/O7au1vppkersng==,iv:LvLX7fYOF/LyPyLUmU3NCeXunX8GdF49hE7xoaxlYC4=,tag:dWxGNzWh5HQUlKojy3OVbg==,type:str]
    #ENC[AES256_GCM,data:jXEVwGexj72ldoV4gsRcHcdBhK9szN/IrK4vggdMQ8C+WPQ5Jb870dNzjRI=,iv:kXPXizyj3DdI8X5wu4HvEOtEM+M5Cpqji09QCjRtCF8=,tag:29+L3DWCV5/ByZZJkpRKhw==,type:comment]
    VIP: ENC[AES256_GCM,data:kP/sUqJuwlImfCsx,iv:nLKmSDgk9f5qLOD+DEw69CkTuek+WwgoZTKGaDK6BPw=,tag:ht17eI6D02HXhw3hKqoE9w==,type:str]
    #ENC[AES256_GCM,data:WcOG5n2mOC4cC2M37StF/oHemHMdj4j7yO2z7G/yLzCRjHpDc1ErinLE9VD2gGkBtzh0Umpr/HH+jIGXglDIn0srSlGp9yKC3+NmF58tCI1ScuYT855+HxI=,iv:gsAqwW96t7jAJb96L64PdA32rd99sjXe3BuDpZN3hc0=,tag:DhUn1ZTdN70XqxnT0l8UiA==,type:comment]
    NUMBER_OF_NODES: ENC[AES256_GCM,data:CA==,iv:0YHsRFU3FrO5/qWWONv9UZdy0BbfpwnZS2xRCAwrwX4=,tag:tqOf8K7gVLoyu4VdX1fA3A==,type:str]
    MASTER1IP: ENC[AES256_GCM,data:eMR9fVeGb071MV9B,iv:CKp0pr7LLo7x+jbrRt+wQROjFGs6YTv70rjjshccSF4=,tag:uAz3im41IWSXiHiErEnGag==,type:str]
    #ENC[AES256_GCM,data:mLtT9tWXt+ZdLMt4uPbo6RYZ9k+QJDkJrA1QYQhhR1RyoQ==,iv:x+/2NwKM3gpvIMX/tPCO0hyo/A0ONu8hrEhwy5LRe8Q=,tag:OC//2JYEMGlie3E7iTyvvA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:XBr8/+DCT0fo4E0=,iv:o5dIgdRuMoZJMn+H16383BT9W+91/QuhsanjOITG5jQ=,tag:uhXgkI5DpKDKOdInd4a5Ig==,type:str]
    #ENC[AES256_GCM,data:bhgV8TqqeunkDYcT5EdOT4G30a+QrQfLjBw=,iv:ASdRO8Jqsdt0Be2FB3jbxCRa8u8PFj1NfvyNPX5sFg4=,tag:r2iIPaivv0yLNKjeGFwsRg==,type:comment]
    NFS_SERVER: ENC[AES256_GCM,data:AKZ4uATq4gzECajH,iv:099fepUgognCHJjokNuJq7j7yBSiklnKQIN9jFEZe2Y=,tag:lhEztnH5dt8KzmBJ34oSBw==,type:str]
    #ENC[AES256_GCM,data:lPAWk9OitB5JNxDJNqCGbyEHGIHYY6u7ryvJjBV9smoGD6j0LamCzM8OVGM8YKc=,iv:2jHQyCyzO6n/3lJMri5F+bVZpd5zL51jO9IzPBFZLxk=,tag:N7pX6tm5ZGkndbcwMF+0zQ==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:FoeUT+iX15Fy71XK1+NUoCgO1F+1AdHDsoGI,iv:5H4YtjvLV11NiOVCiAWI2TNFM30Kt9gisvToQE9EvUU=,tag:e0H+cUIy3cRdFOrpSCIjYA==,type:str]
    #ENC[AES256_GCM,data:ml8RKmeHU7MuWj26gbyo4PoruAFQAG8o+b1Azs3tx+VbNK7qTLjos26d,iv:iGUA8Oz0lEBA5oO38dqHJRydzDGux8L6LZqlP0f+Bu4=,tag:7avRcYayHBQDKE11uNgNIg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:O67V4OP7iKca3bp8nw==,iv:PPs13uvmB0ed+EPAhjTLK3Mc89ltr+R4PZWhirItXIM=,tag:o1fbg/kJ6j3HNYUSudtAaQ==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:daoMR4t1BgBjfCx52A==,iv:pHE4/d/p3yv7y+hBjJDkMk5mfKs+V7R56H+7ufQDpk8=,tag:ZaeRTOcwR1EnV/0yXkrfIQ==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:hUDoYgiwZm/sRf4H9A==,iv:9E9DEPjcpFRUGf5IDcOlcgcoPz+mLCiYO9wEJCslyyQ=,tag:iCpVQA5bMfU0QK8/uJkxBQ==,type:str]
    #ENC[AES256_GCM,data:nQAvZDyDjld3JPbl,iv:wBP6fa3YOs5hiChvt31GKppJEvFa1OYPuSj0zd37Rls=,tag:S8C3+hgtISHl+AXW+f7MAA==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:5ChSKswq,iv:219mS7zd8PVOf/rVEGYNe2L+yl1YBicnLBeRrZ+LVqo=,tag:fKn5iozR5XkL4wRGD2BVQw==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:hx8LuFwSjBT1hfr8Dp8=,iv:luqJnluG4jvKpomIy85oa7NHwmiCu8e9W0ikxqE3F74=,tag:YkU5AVN+NTK5mLv+AIH4yg==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:ELgCqXeaT1qNTzh5IFU=,iv:161HwWlvd4go/qluNoqU0qiGQRIRCDRcFKJ07F77XCU=,tag:7kCN2xxJrV4OEdY3unigLw==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:yKKfLh6FtwDF2Lf9smxj+05f1uUJPRo=,iv:4zcCZRXpjkmGECW3BZ4DARmjFHv9hr1mSQYhcM1sgnY=,tag:Dxy1dXm1GUUv1mhvafwBEw==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:/NzL/F18MPNeEGG49nupT1V1sV5ZBZ2l9dbVlk/WqwcXWlWf2nZytg==,iv:6paljgPKnyyOvMdaQZLne15GLqpvpxJ0U3ch3zi0x5A=,tag:eyu6XUSRkHcO3PiCt+HFIw==,type:str]
    EMAIL_GMAIL: ENC[AES256_GCM,data:OR+V0hzXWa+BGIdlcCWYTA==,iv:ZSgYd9IIDUlBJqEE4PbomN4wTZF+AQ4VM3SaGcYLtfI=,tag:+mYVXsqgIfmn/zqCrUiZSg==,type:str]
    EMAIL_GMAIL_PASSWD: ENC[AES256_GCM,data:tsOTwR4WxHIe7T2C8+D4uA==,iv:Z4ViVN6pFuvEmPyUwSzZ6cYHQL97JJ5t+RbWFDXsIqY=,tag:n+4UuLuUfKsnVJ6I95Khzw==,type:str]
    LDAP_BASE_DN: ENC[AES256_GCM,data:buQ3eTLiW7nhLQkgGzDM7ZEgxDmQDPxe3AKnVg==,iv:ryH3wZMz1kVStOA0EVR+XECdbt82C4iO0xX3IzafqfY=,tag:ea9pDTnuhwaeggpf0RlpwQ==,type:str]
    LDAP_ADMIN_EMAIL: ENC[AES256_GCM,data:gdKOKRC3PFHqffu0LwvDqJg=,iv:LR8cKu6G0fJNtLqaeMB2PySLgPdSmgpbOSWE0S8dJOE=,tag:G0GOnQT0bwmCZzK+uEv8Gg==,type:str]
    LDAP_ADMIN_PASSWD: ENC[AES256_GCM,data:tvyRrvmkN/lGguZraDlsa4Q=,iv:OvN4QZ0HC7ydhp5zsKBv/DZHcNtrpP5kepwZn5zVgso=,tag:sgZ9+4hU7MoBPR8AEI6Ufg==,type:str]
    CNPG_PASSWD: ENC[AES256_GCM,data:qzIqR/e5OUz6AZxd+QxnYhxjgw==,iv:biZONIwt9L7yG2Ba3t77Bjl2RWGbSaZOrJOSzEyIlDc=,tag:htrBScEs8P/S9dhW0w1tRA==,type:str]
    BACKBLAZE_URL: ENC[AES256_GCM,data:wg2lSCCkvBd9KTUwKHq5q9HMdOKkZFMHlGZB9p3Ji8LOnESbAhg=,iv:kCx5ieFiufT54XpV/vzPk5dCj/uIMzFKvlb4iOcb1Cs=,tag:fBaweSQ2b8BsFuR+46Z+vg==,type:str]
    BACKBLAZE_BUCKET: ENC[AES256_GCM,data:Ss62aOJEkcTMHryj,iv:REnOkF3tPRm4Xgp7XRMezHtPz6f2EqDk00PInGZoaUE=,tag:T1CxsdEW8XS0a0fkEM1OuQ==,type:str]
    BACKBLAZE_ID: ENC[AES256_GCM,data:9OeKlZJW8x1oHNr20E8LqufOV6IDZ9ABmw==,iv:pWyJG+u251r5gh9GUlm7DtBp7jVBGmDkdhqqlDWIPKo=,tag:voEY60lv0UiAJCyYVVLP5w==,type:str]
    BACKBLAZE_KEY: ENC[AES256_GCM,data:Bm/kyeZO6uUxfdRZBSx9wogbYzEo6YTjxAS4PCZvtA==,iv:0tEZW+FRN2HdHYXxO5ZYiTg4lLb/TUZTOEALRWhUcvA=,tag:dWylidcyJobT6bAILHr97g==,type:str]
    BACKBLAZE_ENCR_KEY: ENC[AES256_GCM,data:iUcnQaOKemjjANTLHwzClWM=,iv:EaUeJfWlgnT2/DWKycX4JFWFFMRCdmo8Hfir8GLJpLQ=,tag:MVZr2uSaxkZj53iLSx4QDQ==,type:str]
    DUO_HOSTNAME: ENC[AES256_GCM,data:FZ4z29hGlNeHEpqLXjprdJrO6kDkElJTablLAw==,iv:JBFXjzb0YGWzHDTPUslLDzqSfEu4swtGjrsXEaa95ME=,tag:8zJiLCQ5P/K+xBVSLvcToQ==,type:str]
    DUO_INTEG_KEY: ENC[AES256_GCM,data:7FMmx8z9rNTWRhySIKHI14VDP6M=,iv:XCmn6iT+CSckqc16hxYXaQkWvUvTQ+3aFgNn0Ayi+to=,tag:UZ6hWKEa4yVlRlKZhPS3Xg==,type:str]
    DUO_API_KEY: ENC[AES256_GCM,data:UIcBLlbww8avEXPFmRPZyrZ/9e4pGztBDYv+Vj8Z/hTHLKxk0934CA==,iv:SLdiUOFXfD7oDnDMo7dGliXHl/ydb5lCVhvP/PL7xTA=,tag:bCqKxsIsM+7XLP6hQx8lyQ==,type:str]
    OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:Q+l/3c9A6iadNHtg6DtscpfV65FAstA1VZYSZHVU0yY=,iv:cBtW/7M4O4tiE5vNj9Yz13e2Xqdb5YdfQfnMGAj/ckI=,tag:MdcY/JTdKEetsFqO3khpsw==,type:str]
    #ENC[AES256_GCM,data:0WnPmFcXS6wgw+FvhyY=,iv:2VQoI67CFNbwjCNQXMVvSQ/tLW1BSHs5XZuXz0/8dTA=,tag:EmpLqDw4PB+ARK44sUA+Zg==,type:comment]
    PODNET: ENC[AES256_GCM,data:0n2GkEvuua8t0OOVPQ==,iv:w+hmvPl1tBxPZj7hhGL4N3ozS9W0Vxv1fffEmjd+JFM=,tag:TKt5SKEoN8ok4lDa8QBH0A==,type:str]
    SVCNET: ENC[AES256_GCM,data:6AjI8tivFL+QM+Ai+g==,iv:9oGnw7QCbmnYiLH+4Z3ewjdE/IHsgrH49y6tvSwAkVc=,tag:6Dd1fgphKeZ3CdE34GcG8Q==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:XY/O7g==,iv:C/4cN/bUAeOZNRluXHXWdULkmhC5y2ICBUk/TjN7l3Q=,tag:0e7vJZZp2h9GKWy/2ANn+g==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBQQ0NpNkh3SUZoRnJoMDNS
            c1hBby9NZ2hVUWw0TWgxK2xMTFBsdVhXWUFZCkl5SmVIMzFpLzJXSmlndjFzQXFO
            SXZLYWtQYVpwUEFWbHV0OEdWRlJaYUUKLS0tIEFvQW83bStFaWlWUzdkMUh4TlN5
            azk1R1dFTE9rbldOVmJnem4vckJiancKBH7ecK1b64N5lpoibHDBbcsk0lxI/7qQ
            qnMC6yvDCuj46qzg6q2TgqbyOg9klJyOIKa8RxWrHs8UzAEfvoTbsw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-23T03:06:06Z"
    mac: ENC[AES256_GCM,data:EiBJ/1WE+sc0YOoJyBQLO1HUcRHcOgjSuzAYgcCiK/kwMXcq6EYbpMvd/bcS6KRDiXnjOG/wleqDAxdwXlqMyjW/sooANTAu8S5O1m6vADeTrwXNqGquk3Sfz7LRbyHyV5cyFZ71oWDjyvkEjiAZ/0e2fhx7wZDQhMXCUZ5x8hc=,iv:5zmkWWSKEmwMYb5iuqZ1dz/c41NvYYc+oswipGHcqdc=,tag:7SroWBEjU0BbQm/nGGUzbw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
