apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:iLqnq/ZE0z5s/NPg83S6VDlrkBl7cwErJAVVQpGyWQN5cp5W325jJ3MfewFlHk90N31UQMd4Rl4=,iv:exJJLxdKWov7ECQ2jt3IRleVxMrRCRhF0dTYZoYXK+I=,tag:eiX/KDWYB4uXxZuhCCAXPQ==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:nCcMeljcW1wawUzGcFgjXhieGzuwcuxptS2TOn1OZRFu49w+YZzvJbATbw==,iv:xqDPYCTWuS/VsykPVZmIWxxth2QPda7IDTyFMLKSIuY=,tag:f3UAbMw2KOIsDrmbJAu9Jg==,type:str]
    #ENC[AES256_GCM,data:oq93CPd/J88flLDGk7MFLXLcI+JmaUDiY2bpsHN4BWlZs2VekWtsz5Dgecw=,iv:9727pOEQO/YlAbBT4BTBUIrrxGpneMo4+W5AL8XMMhw=,tag:+81rSi0AnaD6fuNe6IyxlA==,type:comment]
    VIP: ENC[AES256_GCM,data:R6gjJqMlB63Xug0A,iv:256w9UrCuMLxsgzM3fj2USHXl18CyCAwMtwyqRHjPpI=,tag:0pWmAO/qHCuWwi4bvFuAJA==,type:str]
    #ENC[AES256_GCM,data:04GE2suD9OZFNdtYaftmKNYhts5dKUsKJBon,iv:T2WAfBp6AiZyIyVUKILF4VfdwGg1U9CQ8az+Cy+ioVI=,tag:wDdno5f91SoOoHoqfizJww==,type:comment]
    #ENC[AES256_GCM,data:Zo8W7UzAMsfvcYtX32s/loTlbmQrV4tBWor4BU2jBP3XOrTRG4zWdY763oFUjHlCsFmSPyZTdg5+ZH1s7prvBwzOYIbYl2tquWXwvpZveVM0P7f7ncrF9hs=,iv:2H8mp2fsrUdDMMXMN/BvAVoDYvZcfD2HVqlCF0dd4sw=,tag:z3LbNLV/HSoXvoHStCkLaw==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:UehmmMsY2ORRpBYe,iv:CxL2x9YJIfoSFCRBeela6EFAaCRcI+CbAA+2gOa9qjQ=,tag:2dFlG4kTLePmUahiJyHYlw==,type:str]
    #ENC[AES256_GCM,data:rdh6ZFmXhWFmqYvxsPCjtLCibZJbdvV8Re7N2awoiK4k8A==,iv:N1csJUYFoqXjVKJzcGE0+3sWK+A+SJ2OF5jf8bw4bMk=,tag:IsyPL6fgSueLQ6gVzVxd9Q==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:bOWKj5qIEqVC3nk=,iv:NvocpmBfKoboM8JuDmHzVOOkWfBBWoqu8LT8KTbNOaE=,tag:sJhXZrwo8AXvl3D0XJT2iA==,type:str]
    #ENC[AES256_GCM,data:Tc+VqVW3Xx9MFnB8GicmTtBabd6L/Fzv2OcH32IKrS3UphzvMIr8gJZbWF+ZEws=,iv:kh64gSDFeK77+QFLimHMS7XMkd/iZCiTOwBJDUC7Jp8=,tag:kmHsUqE1uagtw9Ab8h+gdw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:BTvQcmL0mpKuA5zEGMQTirvhaU1uCPCrVC6R,iv:H9noxKYEwWsHw9do+7wikRWrM987wTghTZ5leKxVdTY=,tag:/GtBxxsjfC9vF3RR6X1Pvg==,type:str]
    #ENC[AES256_GCM,data:LPI6NF/M42lznFs8p7pP+BDFKpeK1rT6ZNGqWRkVcReVT3vcdXWIrKrA,iv:OhQvFZYCUwvbruC6LXdbJ2TvW8hQUOWiZzy0SaIgbxQ=,tag:FFW1LGCg/WxwxgwCvw5Esg==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:hm6Z8QkAqW1ZXjy/HQ==,iv:14bgN3PDQyqOOPb51yDu8D59GJFtQxbuIY0PYr8jZSM=,tag:MMLncCbGcsOIk02cEjvLdw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:cY9RqcUsag8W4ZbBhw==,iv:WVsw1YC8zyYMAezJGg85LfiEOII01aQ4qSJ3UVHoPOI=,tag:yUxa2aFVQ4qEE6U5napVTw==,type:str]
    BLOCKY_IP: ENC[AES256_GCM,data:n8kzvc/7OhUkk/7gjA==,iv:oGhjRuVpVjDf9QRiaF8IdSC/0c7TZ0pqnzUF/fc2zfI=,tag:CywcGDZcGmQhj5RSNPsFuQ==,type:str]
    #ENC[AES256_GCM,data:TGQ6vC2PflswQOOC,iv:B+9+HUz/AOLod5IAHiVfHXSo0FBrKSi20a4Tp0nl16k=,tag:1XUHX2u9GfVrJiyKdeUnAQ==,type:comment]
    DOCKERHUB_USER: ENC[AES256_GCM,data:ZPMIMkhD,iv:EJ6O81HEd/FuzPo0bXV7jya/EXBUt99TJEYGlRe6Gmo=,tag:l6XmsqtJ5kNaJofHt4kdTA==,type:str]
    DOCKERHUB_PASSWORD: ENC[AES256_GCM,data:XPv0s/JiVJoqulM8x20=,iv:DtTlR7nQC18U5sC37mo1Ddq2dB1WxWY6cp9XncjOncM=,tag:iABT7AWO5R8topvuNdMHRg==,type:str]
    DOMAIN_0: ENC[AES256_GCM,data:IDZpN/8lzqy3PU5naxI=,iv:dzSLJCx0vqG+S2MQUv4JxAtY149bQdbVYkT5/RhGMIY=,tag:QMECjtrRTvw6vlILIV5Thg==,type:str]
    DOMAIN_0_EMAIL: ENC[AES256_GCM,data:Tx5UaSsGT+9MD3WLNjbcjil0u9Jh+jQ=,iv:xywavkAiic3d9UrCRlgRUECLtzCpAkSylAoG8DAEAZo=,tag:xrvKW6Y5J9LG0ieih4NTTA==,type:str]
    DOMAIN_0_CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:JUHVsB7RojOkLA+tImG/0LjK+X3JnvOqs0BehPz2Ia35+0ld8e33NQ==,iv:t1nE5dxzZH3EZec/AlbeJb1d2t67kdN0fG0qo0SdCME=,tag:VWpf9Q+4GOAmfI0KWCe/WA==,type:str]
    EMAIL_GMAIL: ENC[AES256_GCM,data:3Glboj4xKWbhzrV6SBeATA==,iv:hUlVBqTIcrp+uMwvcTciFhakauRoPj8imQ23ISIo5Jg=,tag:vGdmRSuTG/yNGIdetdLFrg==,type:str]
    EMAIL_GMAIL_PASSWD: ENC[AES256_GCM,data:glLMPCeKD+EcQKgBBgUOEA==,iv:OqrvVmUXLh2lkjuWsrkFdOOboL4K/ck1bEK64aauQvk=,tag:V+6aqAmRPwUCGjfnIUkoKw==,type:str]
    LDAP_BASE_DN: ENC[AES256_GCM,data:4FjXDImdmo7C+ZUkuTJDTDpq7C9ItVvORFKwZA==,iv:bfjEvalSsgndoNk+PDZGO9pbQ56rGRzN8MSy70+Puoc=,tag:YCO9JTuN2uDGHTx7+2uPLg==,type:str]
    LDAP_ADMIN_EMAIL: ENC[AES256_GCM,data:/AqUnATCjt4fTQOXjq1PULo=,iv:yqx8VPcl70cUxRJw9XbmszfbVVaOf2dwZcJ9nXIl39E=,tag:LmKFj9LbmEDSNStr1dXnrw==,type:str]
    LDAP_ADMIN_PASSWD: ENC[AES256_GCM,data:sahmYZpJgkxWEY9xKkEybbc=,iv:0fseBHQQGkrwGA8UL1xtG65lY7FAJA4ZO8QL1er/b3s=,tag:5uHFISzenWcSOFzzNr6PIg==,type:str]
    CNPG_PASSWD: ENC[AES256_GCM,data:ZNkGsQXmkpAUUWS608Sh7VFShg==,iv:zu1UAJRHKiRfznPXCCyCPZIN58b/sLYXZh8EzHkdWG4=,tag:4HRovgWkjnX20sz+KsF/RQ==,type:str]
    BACKBLAZE_URL: ENC[AES256_GCM,data:nGzY58YsCMRXKYHBPos4LIYIFLcH5huXDWNzhw0zdiJSU5rYTQ4=,iv:M35FcLcuw+I/9bvNjVf2ntGXOrwiYYlhUO8pCnb+ryw=,tag:pOHCoz+vMTDibRwqD6bx2A==,type:str]
    BACKBLAZE_BUCKET: ENC[AES256_GCM,data:sKNF1CANRj7317aa,iv:5erRAlgj/NKiFhs3pvcrQ0bAzBwVzMq1sZKNYCdYfhQ=,tag:WrmN9AIhVb1tHEMcACWUnQ==,type:str]
    BACKBLAZE_ID: ENC[AES256_GCM,data:YAAHq8YRMs9/UMTSXjD10RXCZIj55Hm97w==,iv:b4qMkuj/k+SRxYk0dRBDy3Q0BrFX/wmkrkRkGVViCNo=,tag:PW2eZw5lZI6ZOi/qzDwJ6w==,type:str]
    BACKBLAZE_KEY: ENC[AES256_GCM,data:pDlJJPXuHMDlr+TciflUk5kT580N5xlantBqN01RRw==,iv:y+8aXs116sqDQmCt7Yx0JpXerD20V+PnykEPqsVFbY8=,tag:NKhikPY4jiGG0aogpCDLDA==,type:str]
    BACKBLAZE_ENCR_KEY: ENC[AES256_GCM,data:/9zMRbXjEeQsS1sGappDeUk=,iv:4HvSvpw91RU39BR8IKaNJOISCaVcUAdOH7ZGw6l5ciY=,tag:0nDWYz49g6y7J80OWoPzQA==,type:str]
    DUO_HOSTNAME: ENC[AES256_GCM,data:z6TJUZna++pQyoN7v/I5wP1ZOgpD0AvNJmP1GA==,iv:adG8vnj+hghhwnIDcgFp4AI0ve0+sOfCK5WxpEKYmQc=,tag:6Qo4ALzC1rv8W7cIo0SxhQ==,type:str]
    DUO_INTEG_KEY: ENC[AES256_GCM,data:1o5mTRQu/2zSS6KsWt5iC7DJow0=,iv:3oxeSAQ6KJJHCEXmCQBZmzDUfAGxZ/cwqaPBBGmVBYI=,tag:jp4ff0E62GJxFzeD6oSEWA==,type:str]
    DUO_API_KEY: ENC[AES256_GCM,data:tqbrJmcuXZgD/6YGFzwk3wYeWQK+tmqIh35sHWpnq1xwSCKYPq/s4A==,iv:RRwbcOk0OmgiV6hTvbTgCJN9s7BCeqWjq9cyHlTu9aM=,tag:P4ryAibfsipwj0fliyft5Q==,type:str]
    OPENWEATHERMAP_API_KEY: ENC[AES256_GCM,data:xYJfd7+KunqIz4HlukWjrMQV9JqI2/tcg4+vI5/8tKA=,iv:HUQivQIGyqEvkDXs1N4XnV4ancbgJ+UoRe7BXXxilEU=,tag:YtrBk3rKZu104qqgB4RYnQ==,type:str]
    #ENC[AES256_GCM,data:ot/oSr1JIhrVBgI+NpI=,iv:fTF3I/NJEK3G2e6fW/sfT6s4QixVokOnuZZJ2AWHRaU=,tag:JjR3avg0O5nO1woeTKXfag==,type:comment]
    PODNET: ENC[AES256_GCM,data:b95O4H4U9JqakeKS3Q==,iv:CeuqoIke0BBQ3NB9FzrHY2m/XNHUDQkLKD2/DDCx4wA=,tag:zwq3+sQbk58HiC9M1zfVcQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:qrvV+shWLDMo8dcAaQ==,iv:6qfD1NGbLPF84xLNqV08RfcV499hTgIdCE4/SGv3718=,tag:OaX/PbdYx8N63aXtR2bVig==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:0nulOQ==,iv:w8D/q8TIgn0m2CT2Wgh0+jMY6i45schliYIoe90fuF8=,tag:rdpB1fVadDYVBmrkD6iiHg==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsaUdBSVRHeE1sNXp4V1po
            eSt1NGt4QURSRUxzWnlyUUNLWTdHY3hKSHpvCnV4aTRzTHdsd1lZVFpRM0RlSGRk
            NE1GK0U0dWdYaTRnMml4dUdWdC9NSGsKLS0tIFlaNXNmVFJyWldKTjhIVFp4cElB
            NjRtYWlTUGQ4bXhJVGVNZ01XZmwvTTAKFswfZ5aoI2ts5XNDZo2f+zfeVwhj1hZk
            2kOIMzHB7WJM5WPQ2JIWndmHjX1kXHKC+CRdNyDxaqWBo8womGrJ3Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-11-24T02:47:39Z"
    mac: ENC[AES256_GCM,data:sJvZhUjSzUhWZwQD9que661rpfI8fX76r25nhCGVYANw2/DZp8tNtjJcN/GWC8hyy9ncifxIY0iBKdisBZgBB1ZQIJaEerXb/NNvT5QPa+LM08RwhS5+oysDsBpyjRXZT8XyKjdmlEhuxv/cUF5r7rILSGXj+WsaxCtYDF18rSw=,iv:53q7BxcymHDEeL9EZnk26mY8UhWhjn5jEn6coXq4F+8=,tag:bqSPAvVPGddsxCDuNwpUgw==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
