apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wx5FWiqk6qspWCnOcdaZu8fvt/kbwkuykusUcTO3DthHFjBpYRgP9ziZv7DjjFPRrX8AfUztuOHyPDVEnbPsdjM9In1y9VE7zH4mykpb2EvTDevk9UHBwifUj2bxl9YzkupXdErVDARDAmrJpDWA/aFR7/FgR24hhv8Xutqob8BDtWTo848XhMpi+ol8CTwcvpLVZexUJ6xDrUP8UUC0RoUI78a0bBhf3EIla89Kd/sutZiBfHQfiE+5bZIKOVX9fRaC2fUyZDsjxyLXZchvl3XBA+5nIhKb/v8/jIfSTUqpQrOI+zsbV6m9j68uVvOixSaKvZG8TzpkaGvmEOY4NZdzpe0xSe+GlVYWLoCi/NE04tS6tmw72PvqG6/ecFhH,iv:Aj5rPYi2YArS57x980LPqOf8w68z7Y2aGgOA5A/Figk=,tag:DT1rR4ho7n9sIB3Q1u9qfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:G+OMuNlVZGaNe/B9HOfFXI1O5eyrJ8FO2k18f4pk7eM5UeMqy8WpH2KQQiMOC33MqVwfBU7i8pTl66EDWsjFvvfHzEQHFNpVKE/bIcaEF1ZoGZ4W/Ns54uFiiTQeRSGQ1Dsl9kVa2470hR+mWYEXv+pCCtG54Cg4wgZPY/wPv31LCshSJMo/L9yMbZE5pqQLsAQcu6FBcv+mLKVR/vlr5j/F3gnesosCy7PpTKZaSI1GNRupSt0/AZFkMuZ114BTHMRVCFs7sa2SXfNPXg==,iv:zD4srR+1abiBeDuzdOfbX5kleT4UZ1GO5sLNpiEEx8w=,tag:XIceTcU76MXTnSrYPDaxFw==,type:str]
    known_hosts: ENC[AES256_GCM,data:OcKWfXCawDlMyKZrkY/nDOpqw0B+U3vXfIdVS8VL2PZ4qcLAn0bGbZmxMmKq8NQGF+I+gEtI4O498JnKEV/4E+cBf0qro14b4AIaabq8/Bw1GzBhwgWn9R19fkd4yIB9LNND2h2BXmwT6mms6qhKBzL3RypqkPpgoNxny+2MNDeOjKiCx6cLXP9biUVcsojTJqOXzffc4WOwiMCbUk5sTL2IbDjLFeYzRaVG,iv:4AzdsAxcy4A+bw/HbQIzejY2etux/ljsG5dnmvxqlkI=,tag:IXmruTiuW/77sWRBZ5bgxA==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwak9Sd3RXUFJGdUtPdzlT
            bm9UK3BNYlRmS2lvQ0pTNFR2anphMGxQOWtRCjFLM3NxZWYwdWszZWozZjQ4bWJq
            aG9TaU54S3B6SHpwOHd4aHQxVDQ3WWMKLS0tIHFvd1VlRTMzS1hGRGlQdDBzRStP
            Q1hYRTMxTy9iaWlteHBBTDdieHVmeGMKhad0oCROU7XlFnuFmSOs7TJFYmUSX8fs
            TMOZpmKHlJcd/nO2A0W69+bGn2VqbCxIIdbA02BonSHvvZQOYj7pSg==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-26T20:50:08Z"
    mac: ENC[AES256_GCM,data:fTjI322e6gOJdFnfQJFe2hSfULQsTr3cnAG0vqRgH3Q4YTw9niKjmZPlbS0TUuthAUS/COB+K9Dd02ffm83Q2U7o3BJ3mv/d1w7gHgS1MOAKIliqub90Zt/mpbJxwCCQ6vH58Bvzs4zUpdZriAYYjlxdeKG3cE1V4kQNqI9op18=,iv:ybg504Zy+nWI9qMM70uV/nBmNb1K1uBTrVywwbyLJ3I=,tag:Fsfd6J/MbyejrDmXopWhNg==,type:str]
    shamir_threshold: 3
    version: 3.13.1
