apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MvI/Ec2qhV14qm/saUPG2vIWq0XNl0kN5+GLRwOHRk5G9wn3vOH3mVmxLL5/iyPi9Og/BT8Agh9IpTFmkXII80yx/IbAGRFMrQpvET3V/MkMIcyBwh7ZLAp/10fAJtjil4HOv1mhoZTSLqnghxUcuNyeUQwvGDApWOpDZjU7wzocgnn5CLidC1tKIh+wQMfdECLKckyzle1ms25VUANrA25oGPf3JxwidS83Irw9w5HR6jhk8Gnxq4g/rp3Xg50gKgJ/3xUtYzHilEuHizuuz9SpS3AXD+I5ctcPc24sZ5BDKIMelQbv5S5hhtZX0D+X6c//gcvV0uwhdTnpJxdAMyigpZku8W0fgaG38Co6x6QCoU0VzegWrMjHK62F+ItZ,iv:RE3DF94HTUMSLNSSUGbw1r4vRSb7Wr90jlUvi/QlHyw=,tag:LoqygMbRKu1GJY+o4IeSMA==,type:str]
    identity.pub: ENC[AES256_GCM,data:5vbfPMDgn5DtG28+HegwXoTTkJhpIIKh+tnEJVpwZcEkT1Q64yMElCoY5IxKAcneabuHDKx4nesSAKmzwq2zndna1cMgtcofRsQdlMgmtUEbOXMKG5n8Fy3NVqtBhtIGrb8NNI1zj6Yi5DgULHbFhHQl89lEei3CuccVNsRVqtorT441iyC9kegYH+oLwdaaSiLiij3HO9/9EB3Ari7TLN6ms54eSh3eguu7JycY3AoqALZI41SPoANfQ37VStFhDIpvted7mgMvoDqETQ==,iv:8lh4r2H2B8Ub71m323plfaHUzzbjFAxktBYmYSUmHbM=,tag:/C/EqKSNNAluSsrI5eKWGw==,type:str]
    known_hosts: ENC[AES256_GCM,data:ARQip8qWqt8iQgnwOxhe5liNvwM5IcF/81PW8w4k++UgITIh8d03NxX2yPA0Zotib2nxhoq35UDSbyod3aTC8U1IfY4GKYJtAoK735Fxt5L0REuDCER6DXkjeOLKr6XC1tdE0cY84wY0GolUitJTLL4St9B9qJcpPBAthwSX/fGHDc5P1JslSoQJq80VzYZYVo7cV/xoKsoA8+UnNHv9GGfnDBgj77HkFij/,iv:4VyPs0I1D5rXbiAndUpdJbaRpmbWAzMUVLSXIn5+asw=,tag:ODw52Eut3niVYkGaBLjDsQ==,type:str]
type: Opaque
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1RXZ2eURGSGpxYSt1dTRT
            NFRIRFcvRnpGSmdBeTFHcnc5NG1LQ1dQYkNnCi9LYUcvUHNMcmY2N2lScWIrZDFp
            Z1hUeEowaFpWekE4MVJTODkxSFRZMkUKLS0tIEM3VHhvTlBldnpPUm5xR0Z2dyti
            Vklya3VoWEVTZlBSUGRFVVpzNzRkK0EKBmGw+ETsZ3zlqJRU484w1lZ3XHI98vXi
            2Q24k+Hr4pNn/y2WyfttglRoCewemsljixptY4ifR/rTzYYgtTXy/A==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    lastmodified: "2026-09-05T03:30:21Z"
    mac: ENC[AES256_GCM,data:+YgYvuVHanbyZ9mzZTGkv82YbTUKe03bsAUpQYf+CvttWV6kxYB0EEWIN6Q+YhFmAlIaO3M5qLVpwV4KJY56qVda7ERz7HUkSOwgMfbeRCZBaZvyUxr/g1zuTdizsm8qmo78y0bZWzCzfBQ/qdrLehcErEP17txCg+hQ+W00jbE=,iv:HXZXpPir1bLmCYwW1gFAU/g/UqbL9UQ2fQLRBcpqdoM=,tag:LC93jGkLZagZLISbdFQGqA==,type:str]
    shamir_threshold: 3
    version: 3.13.1
