apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dZLrYqR076TyOTLfMkUWX8FH2F5TeE5KDvHoTceiwT+j6e1LlbqdduKMPjbiCWZJuKcplO4gE6wn6wO3Mab5zj/WoEq7InpuiaXVr8GfppqSX255R2gl4/6cd26ZyPEjLUDwO4betZIMnwpyV6/Vyic5xWVyRVh2ckXwIijG3x01KFfjdmKPPCcbAEOVtfi4oEXm40ti5Zq6nCps8eVepmMSARjbpld72A72xmGOTkNHW/B424VJJTHt6zjQ3icYdAq47QPamY8WYR2LcMNERzOq3s1TZ6x3EMtUArFzuyFD02Gc+1ZgwnrccglIKnjYH3DdYMTkU7oTwaAfBK5MrkrdAcPnverWPNu9sL1Gmqb+zpGTyar4Fopoa9vsnH9Z,iv:DVRCKyHwXj3SC0bjjylf7MxAojAIxwwUTRQA8eYwYAc=,tag:BKRh81bQQT5JpT8cl39s1Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:Mqnjd9CNcKDVlLThNayk6eTIGTCKZ6fk8wbuvNUt+Tor2q0jxGpfqdymIuTajUjV7C5lLQM7LSBJwcY249WhW/G5tXf0QoC6eax1rQ2pbav2SyjzMjK7bgf+rWWNvxwDymZyA8hbFaBSA4ETnNejqWlH6VAYle1fW268L9lPptx3EdDyTAOteezL7mND8haH0pJZj9B51pPmy5lo8C3etRaFpLuprdWs1R+eJiAKaVdSu8X5b5oLXSot/b1geNhe6nQUDxUe3c5h1kqHCg==,iv:fi2yvFfwVx64SnVWGPZ32whM3v5YVLhxUqJ85Ip+kRs=,tag:YMM9KVR/inL5MAdt2ZHygg==,type:str]
    known_hosts: ENC[AES256_GCM,data:G8SMi0gpCAVW2FAA+xpWyfHkPhQNBNX7OJkogDmI/D0NzuVaSyUQommIkDdT3iQxSFZEn+d4/7x4pC+jL2YDGwwj6JGW2ZWc6pG1+tM9rJjQkLalClwwnBSkWVCUVtS+newOVykAS/3GUvrC5h1N53Jmz2eziKiJpTYwHwT6RfLSmDtuWvxSrHp639cGnLu1EUla7rvb0+XnlPZ+R30e3XZFxxB5jCsV5W3f,iv:m+iMD8C9y/47muNjVsZs4ghypkCU5Y/J1+Iwb666r88=,tag:vMkNVbBZL1R5Mm3AqwOpqQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age1nvyuzu5f6y5q6navmgp3xfjgtdyknqa9skle4kc40mdmngrvpfpszpvekr
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXcmZLUk5SSU5IbkhvZzhG
            Y2drMHhyWlE0SVQrM1IvRFdyc1pITTRVZmdrCkpVWUk3TnlLb0pVSFM4MGpMdmEw
            TWZBZkR0RWs0S3gzUVlXR1R0R0E4MnMKLS0tICtUZXcvWXhzdmRYUHZFYlRLS0k0
            QXVWWEQ0UkV4M2dwV2dqVmp1ZHhKSkUK4VCynmnn5AQyY/xPlMW2JkG5062RwPr9
            S77iuJ2IMQT7K1OPWNIZi6WFIV0pHiWw2XFItVHiCto7Z90w/uEQWw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-28T21:22:43Z"
    mac: ENC[AES256_GCM,data:leAB/3B2ia8vb9ndris8R1mwEgTvxRb60UuEbtktFcafZzbUP5imDq7+qTYvUJHIxXKQiUdvnigat0zGNyaSdoSzNEFL4/CEE3UDApRQZQp6BR+65IsC32601bCUKUSN6jUaHiRnKzjD5LEYlGmH5r4oqNxH9hRZBBEj45GkFS4=,iv:+0pyr1q9K49i93HC3z2CWvG5n6oN7Attr2MW13JTKhU=,tag:dYXBp/oTXkMb6FybGBBtNA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.11.0
