apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: nextcloud
  namespace: nextcloud
spec:
  interval: 15m
  chart:
    spec:
      chart: nextcloud
      version: 32.8.9
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        name: backblaze
        type: s3
        path: ""
        accessKey: "${BACKBLAZE_ID}"
        bucket: "${BACKBLAZE_BUCKET}"
        encrKey: "${BACKBLAZE_ENCR_KEY}"
        secretKey: "${BACKBLAZE_KEY}"
        url: "${BACKBLAZE_URL}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            cleanupTempPVC: true
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
      html:
        volsync:
          - name: html
            type: restic
            credentials: backblaze
            cleanupTempPVC: true
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 15 9 * * *
      data:
        enabled: true
        type: nfs
        path: ${NFS_NEXTCLOUD_PATH}
        server: ${NFS_SERVER}
    cnpg:
      main:
        user: nextcloud
        database: nextcloud
        password: ${CNPG_PASSWD}
        pgVersion: 15
        hibernate: false
        mode: recovery
        cluster:
          instances: ${NUMBER_OF_NODES}
          singleNode: ${SINGLE_NODE}
        backups:
          enabled: true
          revision: "1"
          credentials: backblaze
        recovery:
          enabled: true
          revision: "1"
          method: object_store
          credentials: backblaze
    service:
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: "nextcloud.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
          homepage:
            enabled: true
            group: Misc
            name: "Nextcloud"
            widget:
              enabled: false
              key: ${NEXTCLOUD_NC_TOKEN}
              username: ${NEXTCLOUD_ADMIN_USER}
              password: ${NEXTCLOUD_ADMIN_PASSWD}

    nextcloud:
      credentials:
        initialAdminUser: ${NEXTCLOUD_ADMIN_USER}
        initialAdminPassword: ${NEXTCLOUD_ADMIN_PASSWD}
      general:
        accessIP: ${TRAEFIK_IP}
        default_phone_region: CA
      previews:
        providers:
          - PNG
          - JPEG
          - BMP
          - GIF
          - Krita
          - MarkDown
          - MP3
          - OpenDocument
          - TXT
          - XBitmap
      clamav:
        enabled: false
      collabora:
        enabled: true
        username: ${NEXTCLOUD_ADMIN_USER}
        password: ${NEXTCLOUD_ADMIN_PASSWD}
        dictionaries:
          - en_US
          - fr_CA
