apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tautulli
  namespace: tautulli
spec:
  interval: 15m
  chart:
    spec:
      chart: tautulli
      version: 20.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      minio:
        name: minio
        type: s3
        path: ""
        accessKey: "${MINIO_ID}"
        bucket: "${MINIO_BUCKET}"
        encrKey: "${MINIO_ENCR_KEY}"
        secretKey: "${MINIO_KEY}"
        url: "${MINIO_URL}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 45 9 * * *
    service:
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-method: 'GET'
          nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/verify'
          nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_0}?rm=$request_method'
          nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
        hosts:
          - host: "tautulli.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Misc
            name: "Tautulli"
            widget:
              enabled: false
              key: ${TAUTULLI_APIKEY}
