apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 23.3.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    addons:
      gluetun:
        enabled: true
        container:
          resources:
            limits:
              truecharts.org/tun: 1
          env:
            FIREWALL: "on"
            FIREWALL_OUTBOUND_SUBNETS: "192.168.0.0/24"
            VPN_TYPE: wireguard
            VPN_SERVICE_PROVIDER: custom
            WIREGUARD_ENDPOINT_PORT: ${WG_ENDPOINT_PORT}
            WIREGUARD_ENDPOINT_IP: ${WG_QBIT_ENDPOINT_IP}
            WIREGUARD_ADDRESSES: ${WG_QBIT_ADDRESSES}
            WIREGUARD_PRIVATE_KEY: ${WG_QBIT_PRIVATE_KEY}
            WIREGUARD_PUBLIC_KEY: ${WG_QBIT_PUBLIC_KEY}
            FIREWALL_VPN_INPUT_PORTS: ${WG_QBIT_INPUT_PORT}
    credentials:
      minio:
        name: minio
        type: s3
        path: ""
        accessKey: "${MINIO_ID}"
        bucket: "${MINIO_BUCKET}"
        encrKey: "${MINIO_ENCR_KEY}"
        secretKey: "${MINIO_KEY}"
        url: "${MINIO_URL}"
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: minio
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 35 9 * * *
      medias:
        enabled: true
        type: nfs
        mountPath: /medias
        path: ${NFS_MEDIAS_PATH}
        server: ${NFS_SERVER}
    service:
      main:
        type: LoadBalancer
      torrent:
        type: LoadBalancer
        loadBalancerIP: ${QBIT_TORRENT_IP}
        integrations:
          metallb:
            enabled: true
        ports:
          torrent:
            port: 60502
    ingress:
      main:
        enabled: true
        hosts:
          - host: "qbit.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_0}"
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Downloads
            name: "qbittorrent"
            widget:
              enabled: true
              enableLeechProgress: true
              username: ${QBIT_USERNAME}
              password: ${QBIT_PASSWORD}
    workload:
      qbitportforward:
        enabled: false
