apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: qbittorrent
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 22.4.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  postRenderers:
  - kustomize:
      patches:
        - target:
            version: v1
            kind: Deployment
            name: qbittorrent
          patch: |
            - op: add
              path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
              value: 1
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    addons:
      vpn:
        type: gluetun
        killSwitch: true
        excludedNetworks_IPv4:
          - 192.168.0.0/24
        env:
          VPN_TYPE: wireguard
          VPN_SERVICE_PROVIDER: custom
          VPN_ENDPOINT_PORT: ${WG_ENDPOINT_PORT}
          VPN_ENDPOINT_IP: ${WG_QBIT_ENDPOINT_IP}
          WIREGUARD_ADDRESSES: ${WG_QBIT_ADDRESSES}
          WIREGUARD_PRIVATE_KEY: ${WG_QBIT_PRIVATE_KEY}
          WIREGUARD_PUBLIC_KEY: ${WG_QBIT_PUBLIC_KEY}
          FIREWALL_VPN_INPUT_PORTS: ${WG_QBIT_INPUT_PORT}
    credentials:
      backblaze:
        name: backblaze
        type: s3
        path: ""
        accessKey: "${BACKBLAZE_ID}"
        bucket: "${BACKBLAZE_BUCKET}"
        encrKey: "${BACKBLAZE_ENCR_KEY}"
        secretKey: "${BACKBLAZE_KEY}"
        url: "${BACKBLAZE_URL}"
    service:
      main:
        enabled: true
        loadBalancerIP: ${QBIT_TORRENT_IP}
        type: LoadBalancer
      torrent:
        loadBalancerIP: ${QBIT_TORRENT_IP}
        type: LoadBalancer
        ports:
          torrent:
            port: 60502
    ingress:
      main:
        enabled: true
        hosts:
          - host: "qbit.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: auth
                namespace: traefik
          homepage:
            enabled: true
            group: Downloads
            name: "qbittorrent"
            widget:
              enabled: true
              enableLeechProgress: true
              username: ${QBIT_USERNAME}
              password: ${QBIT_PASSWORD}
    persistence:
      config:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 35 9 * * *
      medias:
        enabled: true
        type: nfs
        mountPath: /medias
        path: ${NFS_MEDIAS_PATH}
        server: ${NFS_SERVER}
    workload:
      qbitportforward:
        enabled: false
