apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
    name: homepage
    namespace: homepage
spec:
    interval: 15m
    chart:
        spec:
            chart: homepage
            version: 9.3.4
            sourceRef:
                kind: HelmRepository
                name: truecharts
                namespace: flux-system
    values:
        service:
            main:
                enabled: true
                type: LoadBalancer
        credentials:
            backblaze:
                name: backblaze
                type: s3
                path: ""
                accessKey: "${BACKBLAZE_ID}"
                bucket: "${BACKBLAZE_BUCKET}"
                encrKey: "${BACKBLAZE_ENCR_KEY}"
                secretKey: "${BACKBLAZE_KEY}"
                url: "${BACKBLAZE_URL}"
        forceConfigFromValues: false
        ingress:
            main:
                enabled: true
                hosts:
                    - host: "home.${DOMAIN_0}"
                integrations:
                    certManager:
                        enabled: true
                        certificateIssuer: domain-0-le-prod
                    traefik:
                        enabled: true
                        entrypoints:
                            - websecure
                        # middlewares:
                        #     - name: auth
                        #       namespace: ""
        persistence:
            config:
                enabled: true
                readOnly: false
                mountPath: /app/config
                volsync:
                    - name: config
                      credentials: backblaze
                      type: restic
                      dest:
                        enabled: true
                      src:
                        enabled: false
