apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 20.0.5
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 30m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    imagemaidImage:
      repository: kometateam/imagemaid
      tag: v1.1.1@sha256:fbec331b36c1473f8a9c4214f55e5b097860476c8a5274eb61a2b85df89e56cc
      pullPolicy: IfNotPresent
    credentials:
      minio:
        name: minio
        type: s3
        path: ""
        accessKey: "${MINIO_ID}"
        bucket: "${MINIO_BUCKET}"
        encrKey: "${MINIO_ENCR_KEY}"
        secretKey: "${MINIO_KEY}"
        url: "${MINIO_URL}"
    persistence:
      medias:
        enabled: true
        type: nfs
        mountPath: /medias
        path: ${NFS_MEDIAS_PATH}
        server: ${NFS_SERVER}
      config:
        targetSelectAll: true
        volsync:
          - name: config
            type: restic
            credentials: minio
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 5 11 * * *
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: "plex.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Misc
            name: "Plex"
            widget:
              enabled: true
              custom:
                key: ${PLEX_APIKEY}
    plex:
      serverIP: ${PLEX_IP}
    resources:
      limits:
        nvidia.com/gpu: 1
    workload:
      main:
        podSpec:
          runtimeClassName: "nvidia"
      imagemaid:
        enabled: true
        primary: false
        type: Deployment
        podSpec:
          containers:
            main:
              enabled: true
              primary: true
              imageSelector: imagemaidImage
              env:
                PLEX_PATH: "/config/Library/Application Support/Plex Media Server"
                PLEX_URL: http://plex.plex.svc.cluster.local:32400
                PLEX_TOKEN: ${PLEX_TOKEN}
                MODE: remove
                SCHEDULE: 08:00|monthly(1)
                PHOTO_TRANSCODER: True
                EMPTY_TRASH: True
                CLEAN_BUNDLES: True
                OPTIMIZE_DB: True
                LOCAL_DB: False
                TRACE: False
              probes:
                liveness:
                  enabled: false
                readiness:
                  enabled: false
                startup:
                  enabled: false
