apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 18.0.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 30m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        name: backblaze
        type: s3
        path: ""
        accessKey: "${BACKBLAZE_ID}"
        bucket: "${BACKBLAZE_BUCKET}"
        encrKey: "${BACKBLAZE_ENCR_KEY}"
        secretKey: "${BACKBLAZE_KEY}"
        url: "${BACKBLAZE_URL}"
    persistence:
      config:
        size: 300Gi
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
              cacheCapacity: 50Gi
            src:
              enabled: true
              cacheCapacity: 50Gi
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: "plex.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
          homepage:
            enabled: true
            group: Misc
            name: "Plex"
            widget:
              enabled: true
              custom:
                key: ${PLEX_APIKEY}
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: "http://plex.${DOMAIN_0}:32400,https://plex.${DOMAIN_0}"
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                PLEX_CLAIM: ${PLEX_CLAIM_TOKEN}
