apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: plex
  namespace: plex
spec:
  interval: 15m
  chart:
    spec:
      chart: plex
      version: 19.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 30m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        name: backblaze
        type: s3
        path: ""
        accessKey: "${BACKBLAZE_ID}"
        bucket: "${BACKBLAZE_BUCKET}"
        encrKey: "${BACKBLAZE_ENCR_KEY}"
        secretKey: "${BACKBLAZE_KEY}"
        url: "${BACKBLAZE_URL}"
    persistence:
      medias:
        enabled: true
        type: nfs
        mountPath: /medias
        path: ${NFS_MEDIAS_PATH}
        server: ${NFS_SERVER}
      config:
        size: 300Gi
        # volsync:
        #   - name: config
        #     type: restic
        #     credentials: backblaze
        #     cleanupTempPVC: true
        #     cleanupCachePVC: true
        #     dest:
        #       enabled: true
        #       cacheCapacity: 50Gi
        #     src:
        #       enabled: true
        #       cacheCapacity: 50Gi
        #       retain:
        #         daily: 1
    service:
      main:
        type: LoadBalancer
        loadBalancerIP: ${PLEX_IP}
    ingress:
      main:
        enabled: true
        hosts:
          - host: "plex.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
          homepage:
            enabled: true
            group: Misc
            name: "Plex"
            widget:
              enabled: true
              custom:
                key: ${PLEX_APIKEY}
    plex:
      serverIP: ${PLEX_IP}
      additionalAdvertiseURL: "http://plex.${DOMAIN_0}:32400,https://plex.${DOMAIN_0}"
    resources:
      limits:
        nvidia.com/gpu: 1
    workload:
      main:
        replicas: ${NUMBER_OF_NODES}
        podSpec:
          runtimeClassName: "nvidia"
