apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: authelia
  namespace: authelia
spec:
  interval: 15m
  chart:
    spec:
      chart: authelia
      version: 29.0.12
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      minio:
        name: minio
        type: s3
        path: ""
        accessKey: "${MINIO_ID}"
        bucket: "${MINIO_BUCKET}"
        encrKey: "${MINIO_ENCR_KEY}"
        secretKey: "${MINIO_KEY}"
        url: "${MINIO_URL}"
    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWD}
        hibernate: false
        cluster:
          instances: ${NUMBER_OF_NODES}
          singleNode: ${SINGLE_NODE}
        backups:
          enabled: true
          revision: "1"
          credentials: minio
        recovery:
          enabled: true
          revision: ""
          method: object_store
          credentials: minio
    service:
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: "auth.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          nginx:
            enabled: true
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Admin
            name: "Authelia"
            widget:
              enabled: false
    authelia:
      theme: auto
      totp:
        issuer: Authelia
        period: 30
        skew: 1
      duo_api:
        disable: false
        hostname: "${DUO_HOSTNAME}"
        integration_key: "${DUO_INTEG_KEY}"
        secret_key: "${DUO_API_KEY}"
        enable_self_enrollment: false
      authentication_backend:
        ldap:
          address: ldap://lldap-ldap.lldap.svc.cluster.local:3890
          implementation: lldap
          base_dn: ${LDAP_BASE_DN}
          user: uid=admin,ou=people,${LDAP_BASE_DN}
          password: ${LDAP_ADMIN_PASSWD}
      session:
        cookies:
          - domain: ${DOMAIN_0}
            authelia_url: https://auth.${DOMAIN_0}
            inactivity: '5m'
            expiration: '1h'
            remember_me: '1M'
      notifier:
        smtp:
          address: submission://smtp.gmail.com:587
          username: ${EMAIL_GMAIL}
          password: ${EMAIL_GMAIL_PASSWD}
          sender: ${EMAIL_GMAIL}
          startup_check_address: test@${DOMAIN_0}
          tls:
            server_name: smtp.gmail.com
            minimum_version: TLS1.2
            skip_verify: false
      access_control:
        default_policy: deny
        rules:
        - domain:
          - "*.${DOMAIN_0}"
          policy: bypass
          resources:
            - ^/api([/?].*)?$
            - ^/identity.*$
            - ^/triggers.*$
            - ^/meshagents.*$
            - ^/meshsettings.*$
            - ^/agent.*$
            - ^/control.*$
            - ^/meshrelay.*$
            - ^/wl.*$
            - ^(/[0-9]*)?/api([/?].*)?$
            - ^/uploads/.*$
        - domain:
          - nextcloud.${DOMAIN_0}
          - lounge.${DOMAIN_0}
          - calibreweb.${DOMAIN_0}
          policy: two_factor
          subject:
            - group:nextcloud_users
        - domain:
          - "*.${DOMAIN_0}"
          policy: two_factor
          subject:
            - group:all_access
    workload:
      main:
        replicas: ${NUMBER_OF_NODES}
        podSpec:
          containers:
            main:
              env:
                AUTHELIA_SESSION_SECRET: ${AUTHELIA_SESSION_SECRET}
                AUTHELIA_IDENTITY_VALIDATION_RESET_PASSWORD_JWT_SECRET: ${AUTHELIA_JWT_SECRET}
                AUTHELIA_STORAGE_ENCRYPTION_KEY: ${AUTHELIA_STORAGE_ENCRYPTION_KEY}
