apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: lldap
  namespace: lldap
spec:
  interval: 15m
  chart:
    spec:
      chart: lldap
      version: 7.6.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        name: backblaze
        type: s3
        path: ""
        accessKey: "${BACKBLAZE_ID}"
        bucket: "${BACKBLAZE_BUCKET}"
        encrKey: "${BACKBLAZE_ENCR_KEY}"
        secretKey: "${BACKBLAZE_KEY}"
        url: "${BACKBLAZE_URL}"
    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWD}
        pgVersion: 15
        hibernate: false
        cluster:
          instances: ${NUMBER_OF_NODES}
          singleNode: ${SINGLE_NODE}
        backups:
          enabled: true
          revision: "2"
          credentials: backblaze
        recovery:
          enabled: true
          revision: "1"
          method: object_store
          credentials: backblaze
    persistence:
      data:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 10 * * *
    service:
      ldap:
        type: LoadBalancer
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: lldap.${DOMAIN_0}
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: auth
                namespace: traefik
          homepage:
            enabled: true
            name: "LLDAP"
            group: Admin
            widget:
              enabled: false
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                LLDAP_HTTP_URL: https://lldap.${DOMAIN_0}
                LLDAP_LDAP_BASE_DN: ${LDAP_BASE_DN}
                LLDAP_LDAP_USER_DN: admin
                LLDAP_LDAP_USER_EMAIL: ${LDAP_ADMIN_EMAIL}
                LLDAP_LDAP_USER_PASS: ${LDAP_ADMIN_PASSWD}
