apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: immich
  namespace: immich
spec:
  interval: 15m
  chart:
    spec:
      chart: immich
      version: 18.1.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      minio:
        name: minio
        type: s3
        path: ""
        accessKey: "${MINIO_ID}"
        bucket: "${MINIO_BUCKET}"
        encrKey: "${MINIO_ENCR_KEY}"
        secretKey: "${MINIO_KEY}"
        url: "${MINIO_URL}"
    cnpg:
      main:
        mode: recovery
        password: ${CNPG_PASSWD}
        hibernate: false
        cluster:
          instances: ${NUMBER_OF_NODES}
          singleNode: ${SINGLE_NODE}
        backups:
          enabled: true
          revision: "1"
          credentials: minio
        recovery:
          enabled: true
          revision: ""
          method: object_store
          credentials: minio
    persistence:
      profile:
        volsync:
          - name: profile
            type: restic
            credentials: minio
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 0 14 * * *
      thumbs:
        volsync:
          - name: thumbs
            type: restic
            credentials: minio
            cleanupCachePVC: true
            dest:
              enabled: true
            src:
              enabled: true
              trigger:
                schedule: 5 14 * * *
      library:
        type: nfs
        path: ${NFS_MEDIAS_PATH}/photos/Immich
        server: ${NFS_SERVER}
      uploads:
        type: nfs
        path: ${NFS_MEDIAS_PATH}/photos/uploads
        server: ${NFS_SERVER}
      external:
        enabled: true
        type: nfs
        path: ${NFS_MEDIAS_PATH}/photos/private
        server: ${NFS_SERVER}
        mountPath: /external
        targetSelector:
          main:
            main: {}
          microservices:
            microservices: {}
    service:
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: "immich.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Misc
            name: "Immich"
            widget:
              enabled: true
              custom:
                key: ${IMMICH_APIKEY}
