apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-service-router
  namespace: external-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 15.6.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        enabled: true
        type: ExternalIP
        externalIP: ${GATEWAY}
        externalTrafficPolicy: Local
        ports:
          main:
            enabled: true
            port: 80
            protocol: http
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/auth-method: 'GET'
          nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/verify'
          nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_0}?rm=$request_method'
          nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'

          nginx.ingress.kubernetes.io/upstream-vhost: "${GATEWAY}"
          nginx.ingress.kubernetes.io/proxy-redirect-from: "http://192.168.0.1"
          nginx.ingress.kubernetes.io/proxy-redirect-to:   "https://router.${DOMAIN_0}"
        hosts:
          - host: "router.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Admin
            icon: "router.svg"
            description: "Home router WebUI"
            name: "Router"
            widget:
              enabled: false
