apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: static-web-server
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/server/static-web-server/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

