apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-service-jetkvm
  namespace: external-service
spec:
  interval: 15m
  chart:
    spec:
      chart: external-service
      version: 16.2.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        enabled: true
        type: ExternalIP
        externalIP: ${JETKVM_IP}
        ports:
          main:
            enabled: true
            port: 80
            protocol: http
    ingress:
      main:
        enabled: true
        annotations:
          nginx.ingress.kubernetes.io/proxy-http-version:  "1.1"
          nginx.ingress.kubernetes.io/proxy-read-timeout:  "3600"
          nginx.ingress.kubernetes.io/proxy-send-timeout:  "3600"
          nginx.ingress.kubernetes.io/proxy-buffering:     "off"
          nginx.ingress.kubernetes.io/configuration-snippet: |
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        hosts:
          - host: "jetkvm.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_0}"
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Admin
            icon: "https://raw.githubusercontent.com/jetkvm/kvm/refs/heads/dev/ui/public/favicon.png"
            description: "Next-gen open-source KVM over IP"
            name: "JetKVM"
            widget:
              enabled: false
