apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cloudflareddns
  namespace: cloudflareddns
spec:
  interval: 15m
  chart:
    spec:
      chart: cloudflareddns
      version: 14.10.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/hotio/cloudflareddns
      pullPolicy: IfNotPresent
      tag: latest@sha256:255b444bd4ebdc4d89552b4cfed6bd9f53ca620e9ef74eff2ca24b2b85d0b234
    securityContext:
      container:
        runAsNonRoot: false
        readOnlyRootFilesystem: false
        runAsUser: 0
        runAsGroup: 0
    cloudflareddns:
      api_token: "${DOMAIN_0_CLOUDFLARE_TOKEN}"
      interval: 300
      host_zone_record:
        - domain: "${DOMAIN_0}"
          zone: "${DOMAIN_0_ZONE_ID}"
          record: A
