---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: traefik
spec:
  interval: 15m
  chart:
    spec:
      chart: traefik
      version: 30.2.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    global:
      stopAll: false
    workload:
      main:
        replicas: ${NUMBER_OF_NODES}
    defaultCertificate: "domain-0-wildcard"
    service:
      main:
        enabled: true
        type: LoadBalancer
      tcp:
        enabled: true
        loadBalancerIP: ${TRAEFIK_IP}
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: traefik.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domaine-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: auth
                namespace: traefik
              - name: traefik-dashboard
                namespace: traefik
          homepage:
            enabled: true
            group: Admin
            name: "Traefik"
            widget:
              enabled: true
    middlewares:
      redirectRegex:
        - name: traefik-dashboard
          regex: https://traefik\.${DOMAIN_0}/?$
          replacement: https://traefik.${DOMAIN_0}/dashboard/#/
          permanent: true
      forwardAuth:
        - name: auth
          address: http://authelia.authelia.svc.cluster.local:9091/api/verify?rd=https://auth.${DOMAIN_0}
          authResponseHeaders:
            - Remote-User
            - Remote-Group
            - Remote-Name
            - Remote-Email
          trustForwardHeader: true
