apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kat-irc
resources:
  - ../app
  - oauth-secret.yaml
configMapGenerator:
  - name: kat-irc-config
    behavior: merge
    files:
      - config.json
patches:
  - path: helm-release.patch.yaml
  - target:
      kind: Secret
      name: kat-irc-openai
    patch: |-
      $patch: delete
      apiVersion: v1
      kind: Secret
      metadata:
        name: kat-irc-openai
