apiVersion: v1
kind: Secret
metadata:
  name: kat-irc-oauth
  namespace: kat-irc
type: Opaque
data:
  # This value is secret, even though it is encoded in base64.
  # Only the user puts it in clusterenv.yaml and runs clustertool genconfig.
  oauth.json: ${KAT_CHATGPT_OAUTH_B64}
