---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: 0.32.1
      sourceRef:
        kind: HelmRepository
        name: home-ops-mirror
        namespace: flux-system
  install:
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    crds: CreateReplace
    remediation:
      strategy: rollback
      retries: 3
  uninstall:
    keepHistory: false
  values:
    volumeMounts:
      - name: headlamp-plugins
        mountPath: /build/plugins
    volumes:
      - name: headlamp-plugins
        emptyDir: {}
    initContainers:
      - name: headlamp-plugins
        image: ghcr.io/headlamp-k8s/headlamp-plugin-flux:latest
        imagePullPolicy: Always
        command:
          - /bin/sh
          - -c
          - mkdir -p /build/plugins && cp -r /plugins/* /build/plugins/
        volumeMounts:
          - name: headlamp-plugins
            mountPath: /build/plugins
    config:
      pluginsDir: /build/plugins
    service:
      type: LoadBalancer
      loadBalancerIP: ${DASHBOARD_IP}
      integrations:
        metallb:
          enabled: true
    ingress:
      enabled: true
      hosts:
        - host: headlamp.${DOMAIN_0}
          paths:
          - path: /
            type: Prefix
      tls:
        - hosts:
            - headlamp.${DOMAIN_0}
          secretName: "headlamp-tls-0"
      annotations:
        nginx.ingress.kubernetes.io/auth-method: 'GET'
        nginx.ingress.kubernetes.io/auth-url: 'http://authelia.authelia.svc.cluster.local:9091/api/verify'
        nginx.ingress.kubernetes.io/auth-signin: 'https://auth.${DOMAIN_0}?rm=$request_method'
        nginx.ingress.kubernetes.io/auth-response-headers: 'Remote-User,Remote-Name,Remote-Groups,Remote-Email'
        cert-manager.io/cluster-issuer: domain-0-le-prod
        cert-manager.io/private-key-rotation-policy: Always
        gethomepage.dev/enabled: "true"
        gethomepage.dev/href: "https://headlamp.${DOMAIN_0}"
        gethomepage.dev/description: "View and manage the Kubernetes cluster"
        gethomepage.dev/group: Admin
        gethomepage.dev/icon: https://raw.githubusercontent.com/headlamp-k8s/headlamp/d8260857d16d28daedfbe8d6f53e1c165a4e4b05/frontend/public/android-chrome-512x512.png
        gethomepage.dev/name: "Headlamp"
