apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  releaseName: longhorn
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: home-ops-mirror
        namespace: flux-system
  install:
    createNamespace: true
    crds: CreateReplace
    remediation:
      retries: 3
  upgrade:
    crds: CreateReplace
    remediation:
      retries: 3
  values:
    defaultSettings:
      defaultReplicaCount: ${NUMBER_OF_NODES}
      # Overprovisioning might be needed when using volsync
      storageOverProvisioningPercentage: 100000
      storageReservedPercentageForDefaultDisk: 5
      # v2DataEngine: true
    persistence:
      # Set to false to pick another CSI as default
      defaultClass: true
      defaultClassReplicaCount: ${NUMBER_OF_NODES}
    csi:
      attacherReplicaCount: ${NUMBER_OF_NODES}
      provisionerReplicaCount: ${NUMBER_OF_NODES}
      resizerReplicaCount: ${NUMBER_OF_NODES}
      snapshotterReplicaCount: ${NUMBER_OF_NODES}
    longhornUI:
      replicas: ${NUMBER_OF_NODES}
    service:
      ui:
        type: LoadBalancer
    ingress:
      enabled: true
      host: longhorn.${DOMAIN_0}
      pathType: Prefix
      tls: true
      tlsSecret: "longhorn-tls-0"
      annotations:
        traefik.ingress.kubernetes.io/router.entrypoints: websecure
        traefik.ingress.kubernetes.io/router.middlewares: "traefik-chain-basic@kubernetescrd,traefik-auth@kubernetescrd"
        traefik.ingress.kubernetes.io/router.tls: "true"
        cert-manager.io/cluster-issuer: domain-0-le-prod
        cert-manager.io/private-key-rotation-policy: Always
        gethomepage.dev/enabled: "true"
        gethomepage.dev/href: "https://longhorn.${DOMAIN_0}"
        gethomepage.dev/description: "View and manage PVCs and snapshots"
        gethomepage.dev/group: Admin
        gethomepage.dev/icon: longhorn.svg
        gethomepage.dev/name: "Longhorn UI"
