apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-delete
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 0 0 * * *
  groups:
  - default
  name: snapshot-delete
  retain: 1
  task: snapshot-delete
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-cleanup
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 15 0 * * *
  groups:
  - default
  name: snapshot-cleanup
  retain: 0
  task: snapshot-cleanup
---
apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: trim
  namespace: longhorn-system
spec:
  concurrency: 1
  cron: 30 0 * * *
  groups:
  - default
  name: trim
  retain: 0
  task: filesystem-trim
