apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vaultwarden
  namespace: vaultwarden
spec:
  interval: 15m
  chart:
    spec:
      chart: vaultwarden
      version: 28.5.0
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      backblaze:
        name: backblaze
        type: s3
        path: ""
        accessKey: "${BACKBLAZE_ID}"
        bucket: "${BACKBLAZE_BUCKET}"
        encrKey: "${BACKBLAZE_ENCR_KEY}"
        secretKey: "${BACKBLAZE_KEY}"
        url: "${BACKBLAZE_URL}"
    service:
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: "vault.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
          homepage:
            enabled: true
            group: Admin
            name: "Vaultwarden"
            widget:
              enabled: false
      admin:
        enabled: true
        primary: false
        targetSelector:
          main: main
        hosts:
          - host: "vault.${DOMAIN_0}"
            paths:
            - path: /admin
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
            - name: auth
              namespace: traefik
    persistence:
      data:
        volsync:
          - name: config
            type: restic
            credentials: backblaze
            dest:
              enabled: true
            src:
              enabled: true
    cnpg:
      main:
        user: vaultwarden
        database: vaultwarden
        password: ${CNPG_PASSWD}
        pgVersion: 15
        hibernate: false
        mode: standalone  # recovery
        cluster:
          instances: 1
          singleNode: true
        backups:
          enabled: true
          revision: "1"
          credentials: backblaze
        recovery:
          enabled: true
          revision: "1"
          method: object_store
          credentials: backblaze
    vaultwarden:
      push:
        enabled: true
        installationId: ${VAULTWARDEN_PUSH_ID}
        installationKey: ${VAULTWARDEN_PUSH_KEY}
