apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: openbooks
  namespace: openbooks
spec:
  interval: 15m
  chart:
    spec:
      chart: openbooks
      version: 6.3.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    service:
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: "openbooks.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          traefik:
            enabled: true
            entrypoints:
              - websecure
            middlewares:
              - name: auth
                namespace: traefik
          homepage:
            enabled: true
            group: Downloads
            name: "Openbooks"
            widget:
              enabled: false
    openbooks:
      user_name: jaja27_openbooks
      server: irc.irchighway.net:6697
      tls: true
    persistence:
      books:
        enabled: true
        type: nfs
        mountPath: /books/books
        path: ${NFS_MEDIAS_PATH}/downloads/openbooks
        server: ${NFS_SERVER}
