apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tracearr
  namespace: tracearr
spec:
  interval: 15m
  chart:
    spec:
      chart: tracearr
      version: 5.4.2
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
  timeout: 20m
  maxHistory: 3
  driftDetection:
    mode: warn
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      minio:
        name: minio
        type: s3
        path: ""
        accessKey: "${MINIO_ID}"
        bucket: "${MINIO_BUCKET}"
        encrKey: "${MINIO_ENCR_KEY}"
        secretKey: "${MINIO_KEY}"
        url: "${MINIO_URL}"
    cnpg:
      main:
        password: ${CNPG_PASSWD}
        hibernate: false
        mode: recovery
        cluster:
          instances: ${NUMBER_OF_NODES}
          singleNode: ${SINGLE_NODE}
          imageName: ghcr.io/jaja360/cnpg-postgresql-timescale:16.15-ts2.29
          preloadLibraries:
            - timescaledb
        backups:
          enabled: true
          revision: "1"
          credentials: minio
        recovery:
          enabled: true
          revision: "1"
          method: object_store
          credentials: minio
    service:
      main:
        type: LoadBalancer
    ingress:
      main:
        enabled: true
        hosts:
          - host: "tracearr.${DOMAIN_0}"
            paths:
            - path: /
              pathType: Prefix
        integrations:
          nginx:
            enabled: true
            auth:
              type: "authelia"
              internalHost: "authelia.authelia.svc.cluster.local:9091"
              externalHost: "auth.${DOMAIN_0}"
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
          homepage:
            enabled: true
            group: Misc
            name: "tracearr"
            widget:
              enabled: true
              custom:
                key: ${TRACEARR_APIKEY}
